const fs = require("fs");
const path = require("path");

const out = path.resolve(__dirname, "../app-content/question_bank_expansion_50.json");

function item(id, category, stem, stemZh, options, answer, rationale, rationaleZh, wrongTags) {
  return { id, category, stem, stem_zh: stemZh, options, answer, rationale, rationale_zh: rationaleZh, wrong_tags: wrongTags };
}

const items = [
  item("P007", "prioritization", "A client with a tracheostomy is making a high-pitched noise and appears anxious. What should the nurse do first?", "氣切病人發出高音調聲音並顯得焦慮。護理師應先做什麼？", [["A","Assess airway patency.","評估呼吸道通暢。"],["B","Offer a writing board.","提供書寫板。"],["C","Document anxiety.","記錄焦慮。"],["D","Call dietary services.","聯絡膳食部門。"]], ["A"], "A high-pitched noise with anxiety may indicate airway obstruction. Airway assessment is priority.", "高音調聲音合併焦慮可能提示呼吸道阻塞，優先評估 airway。", ["prioritization","cue_recognition"]),
  item("P008", "prioritization", "Which client should the nurse assess first on a medical unit?", "內科病房中護理師應先評估哪位病人？", [["A","A client with potassium 2.8 mEq/L and muscle cramps.","鉀 2.8 mEq/L 且肌肉抽筋的病人。"],["B","A client requesting a second pillow.","要求第二個枕頭的病人。"],["C","A client asking about visiting hours.","詢問探視時間的病人。"],["D","A client with dry skin requesting lotion.","皮膚乾燥要求乳液的病人。"]], ["A"], "Severe hypokalemia can cause dysrhythmias and requires prompt assessment.", "嚴重低血鉀可造成心律不整，需要及時評估。", ["knowledge_gap","prioritization"]),
  item("P009", "prioritization", "A client with a head injury becomes increasingly drowsy and vomits. What is the priority?", "頭部外傷病人越來越嗜睡並嘔吐。優先處理是？", [["A","Assess neurological status and escalate care.","評估神經狀態並升級處理。"],["B","Offer clear fluids.","提供清流質。"],["C","Encourage sleep.","鼓勵睡覺。"],["D","Provide routine discharge teaching.","提供例行出院教學。"]], ["A"], "Worsening drowsiness and vomiting after head injury may indicate increased intracranial pressure.", "頭傷後嗜睡加重和嘔吐可能提示顱內壓升高。", ["cue_recognition","prioritization","safety_infection"]),
  item("P010", "prioritization", "Which postoperative finding requires immediate follow-up?", "術後哪個發現需要立即追蹤？", [["A","Urine output 15 mL/hr for 2 hours.","尿量連續 2 小時每小時 15 mL。"],["B","Incisional pain 3/10 after analgesia.","止痛後切口疼痛 3/10。"],["C","Mild thirst.","輕微口渴。"],["D","Requests family visit.","要求家屬探視。"]], ["A"], "Low urine output may indicate poor perfusion or fluid imbalance and requires prompt follow-up.", "尿量低可能提示灌流不足或液體失衡，需要及時追蹤。", ["cue_recognition","prioritization"]),

  item("D005", "delegation_scope", "Which task should the RN keep rather than delegate?", "哪項任務應由 RN 保留而不是委派？", [["A","Initial assessment of a newly admitted client.","新入院病人的初始評估。"],["B","Obtaining a stable client's weight.","測量穩定病人體重。"],["C","Assisting with routine feeding.","協助例行進食。"],["D","Transporting a stable client.","運送穩定病人。"]], ["A"], "Initial assessment requires RN judgment and should not be delegated.", "初始評估需要 RN 判斷，不應委派。", ["delegation_scope"]),
  item("D006", "delegation_scope", "The RN delegates vital signs to UAP. Which instruction is best?", "RN 委派 UAP 量生命徵象。哪項指示最好？", [["A","Report systolic blood pressure below 90 immediately.","收縮壓低於 90 立即回報。"],["B","Decide whether to hold medications.","決定是否停藥。"],["C","Assess the cause of fever.","評估發燒原因。"],["D","Teach the client about hypertension.","教病人高血壓知識。"]], ["A"], "Delegated tasks should include clear reporting parameters. Medication decisions, assessment and teaching remain RN functions.", "委派任務應有明確回報標準；藥物決策、評估與教學屬 RN 職責。", ["delegation_scope","safety_infection"]),
  item("D007", "delegation_scope", "Which client is most appropriate for an experienced LPN/LVN under RN supervision?", "哪位病人最適合在 RN 監督下由有經驗 LPN/LVN 照護？", [["A","A stable client receiving routine oral medications.","穩定且需例行口服藥的病人。"],["B","A client with sudden respiratory distress.","突然呼吸窘迫的病人。"],["C","A new admission requiring initial assessment.","需要初始評估的新入院病人。"],["D","A client requiring complex discharge teaching.","需要複雜出院教學的病人。"]], ["A"], "Stable, predictable care is more appropriate than unstable assessment or complex teaching.", "穩定且可預期的照護較合適；不穩定評估和複雜教學不適合。", ["delegation_scope","prioritization"]),
  item("D008", "delegation_scope", "Which statement by UAP requires RN follow-up?", "UAP 哪句話需要 RN 追蹤？", [["A","I will report if the client becomes short of breath.","如果病人呼吸困難我會回報。"],["B","I will teach the client how to use the incentive spirometer.","我會教病人使用 incentive spirometer。"],["C","I will help the stable client bathe.","我會協助穩定病人洗澡。"],["D","I will record the intake amount.","我會記錄攝入量。"]], ["B"], "Teaching requires RN responsibility and should not be performed by UAP.", "教學屬 RN 職責，不應由 UAP 執行。", ["delegation_scope","english_wording"]),

  item("PH009", "pharmacology", "A client taking spironolactone asks about diet. Which food should the nurse caution about?", "服用 spironolactone 的病人詢問飲食。護理師應提醒哪類食物？", [["A","High-potassium foods.","高鉀食物。"],["B","Low-fiber foods.","低纖食物。"],["C","Foods with vitamin C.","含維生素 C 食物。"],["D","Dairy products only.","僅乳製品。"]], ["A"], "Spironolactone is potassium-sparing; excessive potassium intake may increase hyperkalemia risk.", "Spironolactone 保鉀，過多鉀攝入可能增加高血鉀風險。", ["knowledge_gap","pharmacology"]),
  item("PH010", "pharmacology", "Which finding should the nurse monitor for a client taking gentamicin?", "使用 gentamicin 的病人應監測哪項發現？", [["A","Hearing changes.","聽力變化。"],["B","Increased appetite.","食慾增加。"],["C","Hair growth.","毛髮增長。"],["D","Improved sleep.","睡眠改善。"]], ["A"], "Aminoglycosides such as gentamicin can be associated with ototoxicity and nephrotoxicity.", "Gentamicin 等 aminoglycoside 可能與耳毒性和腎毒性相關。", ["knowledge_gap","cue_recognition"]),
  item("PH011", "pharmacology", "Which client statement about metformin requires follow-up before a contrast study?", "使用 metformin 的病人在造影檢查前哪句話需要追蹤？", [["A","I take metformin for diabetes.","我因糖尿病服用 metformin。"],["B","I will bring my medication list.","我會帶藥物清單。"],["C","I will report kidney problems.","我會回報腎臟問題。"],["D","I understand my provider may give special instructions.","我知道醫師/團隊可能有特別指示。"]], ["A"], "Metformin use around contrast studies may require provider instructions due to kidney/lactic acidosis concerns.", "Metformin 在造影檢查前後可能需特殊指示，涉及腎功能/乳酸酸中毒風險。", ["knowledge_gap","safety_infection"]),
  item("PH012", "pharmacology", "A client taking lithium reports vomiting, diarrhea and tremor. What should the nurse suspect?", "服用 lithium 的病人回報嘔吐、腹瀉和顫抖。護理師應懷疑什麼？", [["A","Lithium toxicity.","Lithium 中毒。"],["B","Expected improvement.","預期改善。"],["C","Low risk finding.","低風險發現。"],["D","Need for extra salt restriction only.","只需額外限鹽。"]], ["A"], "Gastrointestinal symptoms and tremor may indicate lithium toxicity and require prompt follow-up.", "胃腸症狀與顫抖可能提示 lithium 中毒，需要及時追蹤。", ["knowledge_gap","cue_recognition","prioritization"]),

  item("S007", "safety_infection", "Which room assignment is best for a client requiring airborne precautions?", "需要空氣隔離的病人最適合哪種房間？", [["A","Negative-pressure private room as available.","可用時安排負壓單人房。"],["B","Shared room with any stable client.","與任何穩定病人共用房。"],["C","Room near cafeteria.","靠近餐廳房間。"],["D","No specific room needed.","不需特定房間。"]], ["A"], "Airborne precautions commonly require a negative-pressure room according to facility protocol.", "空氣隔離通常需按機構流程安排負壓房。", ["safety_infection","knowledge_gap"]),
  item("S008", "safety_infection", "A confused client pulls at IV tubing. Which action is best first?", "混亂病人拉扯 IV 管路。最先合適的行動是？", [["A","Assess causes and use least restrictive safety measures.","評估原因並使用限制最少的安全措施。"],["B","Apply restraints immediately without assessment.","未評估立即約束。"],["C","Ignore the behavior.","忽略行為。"],["D","Remove the call light.","移除呼叫鈴。"]], ["A"], "Safety care should assess causes and use least restrictive interventions before restraints unless immediate danger requires otherwise.", "安全處理應先評估原因並採用限制最少措施，除非有立即危險。", ["safety_infection","prioritization"]),
  item("S009", "safety_infection", "Which action is best when a client begins to have a seizure in bed?", "病人在床上開始抽搐時，哪項最合適？", [["A","Protect the client from injury and turn to side if possible.","保護病人免受傷並可行時側臥。"],["B","Put a spoon in the client's mouth.","把湯匙放進病人口中。"],["C","Hold the client down firmly.","用力壓住病人。"],["D","Leave to find family first.","先離開去找家屬。"]], ["A"], "Seizure safety focuses on injury prevention, airway support and not placing objects in the mouth.", "癲癇安全重點是防傷、支持 airway，不把物品放入口中。", ["safety_infection","knowledge_gap"]),
  item("S010", "safety_infection", "Which action supports oxygen safety at home?", "哪項支持居家氧氣安全？", [["A","Keep oxygen away from open flames.","讓氧氣遠離明火。"],["B","Smoke near oxygen if window is open.","窗戶打開即可在氧氣旁吸菸。"],["C","Use petroleum jelly near oxygen tubing.","在氧氣管附近使用凡士林。"],["D","Store oxygen beside a heater.","把氧氣放在暖爐旁。"]], ["A"], "Oxygen supports combustion; keep it away from flames and heat sources.", "氧氣助燃，應遠離火源與熱源。", ["safety_infection","english_wording"]),

  item("MC005", "maternal_child", "A newborn is jittery and has poor feeding. Which assessment is priority?", "新生兒顫抖且餵食差。優先評估是？", [["A","Blood glucose.","血糖。"],["B","Hair color.","髮色。"],["C","Parent preference for clothing.","家長衣物偏好。"],["D","Room decoration.","房間裝飾。"]], ["A"], "Jitteriness and poor feeding may indicate hypoglycemia in a newborn.", "新生兒顫抖和餵食差可能提示低血糖。", ["maternal_child","cue_recognition","prioritization"]),
  item("MC006", "maternal_child", "Which postpartum finding should the nurse report promptly?", "產後哪個發現應及時回報？", [["A","Saturating a perineal pad in 15 minutes.","15 分鐘浸透一片產墊。"],["B","Mild afterpains while breastfeeding.","哺乳時輕微宮縮痛。"],["C","Fatigue after visitors leave.","訪客離開後疲倦。"],["D","Moderate thirst.","中等口渴。"]], ["A"], "Rapid pad saturation suggests excessive bleeding and requires prompt action.", "產墊快速浸透提示出血過多，需要及時處理。", ["maternal_child","prioritization","safety_infection"]),
  item("MC007", "maternal_child", "A laboring client has recurrent late decelerations. Which action is appropriate?", "產程中胎心反覆 late decelerations。哪項行動合適？", [["A","Reposition the client and notify the provider per protocol.","協助變換體位並按流程通知醫師/團隊。"],["B","Encourage pushing regardless of dilation.","不管開指情況鼓勵用力。"],["C","Ignore if the mother feels well.","若產婦感覺良好就忽略。"],["D","Offer routine discharge teaching.","提供例行出院教學。"]], ["A"], "Late decelerations may indicate uteroplacental insufficiency and require intrauterine resuscitation actions and escalation.", "Late decelerations 可能提示子宮胎盤供血不足，需要相應處理和升級通報。", ["maternal_child","cue_recognition","prioritization"]),
  item("MC008", "maternal_child", "Which instruction is important for a parent placing an infant to sleep?", "家長安置嬰兒睡眠時哪項指導重要？", [["A","Place the infant on the back to sleep.","讓嬰兒仰睡。"],["B","Use loose blankets around the face.","臉周圍放鬆散毯子。"],["C","Place pillows in the crib.","嬰兒床放枕頭。"],["D","Use prone position routinely.","例行趴睡。"]], ["A"], "Back-to-sleep positioning reduces sleep-related infant risk.", "仰睡可降低嬰兒睡眠相關風險。", ["maternal_child","safety_infection"]),

  item("MH006", "therapeutic_communication", "A client says, 'I am angry that no one listens.' Which response is best?", "病人說：『我很生氣，沒有人聽我說。』最佳回應是？", [["A","Calm down first.","你先冷靜。"],["B","I can see you are angry. Tell me what happened.","我看得出你很生氣，告訴我發生了什麼。"],["C","There is no reason to be angry.","沒有理由生氣。"],["D","Other clients have worse problems.","其他病人問題更嚴重。"]], ["B"], "The response acknowledges emotion and invites expression.", "此回應承認情緒並邀請表達。", ["therapeutic_communication"]),
  item("MH007", "therapeutic_communication", "Which response is best for a client expressing fear before a procedure?", "病人在操作前表達恐懼，哪個回應最佳？", [["A","Tell me what you understand about the procedure.","告訴我你對這個操作的理解。"],["B","It is not scary.","這不可怕。"],["C","Everyone does fine.","每個人都沒事。"],["D","Do not ask questions now.","現在不要問問題。"]], ["A"], "Assessing understanding helps identify concerns and supports teaching.", "評估理解有助於找出擔憂並支持教學。", ["therapeutic_communication","english_wording"]),
  item("MH008", "therapeutic_communication", "A client with panic reports feeling unable to breathe. Which action is best?", "恐慌病人表示覺得無法呼吸。哪項行動最佳？", [["A","Stay with the client and speak in a calm, simple manner.","陪伴病人並用平靜簡短語言說話。"],["B","Tell the client to stop overreacting.","告訴病人不要反應過度。"],["C","Leave the client alone to calm down.","讓病人獨自冷靜。"],["D","Use complex explanations.","使用複雜解釋。"]], ["A"], "Presence and calm simple communication support safety during panic.", "陪伴與簡短平靜溝通有助於恐慌時的安全。", ["therapeutic_communication","safety_infection"]),
  item("MH009", "therapeutic_communication", "A client refuses medication and says, 'You are trying to poison me.' Which response is most therapeutic?", "病人拒藥並說：『你們想毒害我。』哪個回應最具治療性？", [["A","That is ridiculous.","這太荒謬了。"],["B","I am not trying to poison you. Tell me what worries you about the medication.","我不是要毒害你。告訴我你對藥物擔心什麼。"],["C","Take it or you cannot eat.","不吃藥就不能吃飯。"],["D","Your belief is completely false.","你的想法完全錯誤。"]], ["B"], "The response does not argue with the belief and explores the client's concern.", "此回應不與信念爭辯，並探索病人擔憂。", ["therapeutic_communication"]),

  item("NGN005", "ngn", "Which cues suggest fluid volume overload? Select all that apply.", "哪些線索提示液體負荷過多？可多選。", [["A","Crackles in lungs.","肺部 crackles。"],["B","Sudden weight gain.","體重突然增加。"],["C","Peripheral edema.","周邊水腫。"],["D","Dry mucous membranes only.","僅黏膜乾燥。"]], ["A","B","C"], "Crackles, sudden weight gain and edema are consistent with fluid overload.", "肺部 crackles、體重突然增加與水腫符合液體負荷過多。", ["cue_recognition","knowledge_gap"]),
  item("NGN006", "ngn", "Which findings indicate possible hypoglycemia? Select all that apply.", "哪些發現提示可能低血糖？可多選。", [["A","Sweating.","出汗。"],["B","Trembling.","顫抖。"],["C","Confusion.","混亂。"],["D","Warm dry skin with fruity breath only.","只有皮膚溫暖乾燥且水果味呼吸。"]], ["A","B","C"], "Sweating, trembling and confusion are common hypoglycemia cues.", "出汗、顫抖和混亂是常見低血糖線索。", ["cue_recognition","knowledge_gap"]),
  item("NGN007", "ngn", "Which actions are appropriate for a client with suspected stroke symptoms? Select all that apply.", "疑似中風症狀病人，哪些行動合適？可多選。", [["A","Note the time symptoms began.","記錄症狀開始時間。"],["B","Perform focused neurologic assessment.","做重點神經評估。"],["C","Delay care until family arrives.","延後到家屬到達。"],["D","Activate emergency/stroke protocol according to facility policy.","按機構政策啟動急救/中風流程。"]], ["A","B","D"], "Stroke care requires time awareness, focused assessment and rapid protocol activation.", "中風照護需要掌握時間、重點評估並快速啟動流程。", ["prioritization","safety_infection"]),
  item("NGN008", "ngn", "Which cues are concerning in a client with possible pulmonary embolism? Select all that apply.", "疑似肺栓塞病人哪些線索令人擔心？可多選。", [["A","Sudden shortness of breath.","突發呼吸困難。"],["B","Chest pain with breathing.","呼吸時胸痛。"],["C","Oxygen saturation 86%.","血氧 86%。"],["D","Requests television remote.","要求電視遙控器。"]], ["A","B","C"], "Sudden dyspnea, pleuritic chest pain and low oxygen saturation are concerning respiratory/perfusion cues.", "突發呼吸困難、呼吸性胸痛與低血氧提示呼吸/灌流風險。", ["cue_recognition","prioritization"]),

  item("E005", "english_wording", "When an option says 'notify the provider,' what should the learner check first?", "選項寫 notify the provider 時，考生應先檢查什麼？", [["A","Whether nursing assessment or immediate safety action is needed first.","是否需先做護理評估或立即安全行動。"],["B","Whether it is the longest option.","是否最長。"],["C","Whether it sounds dramatic.","是否聽起來嚴重。"],["D","Whether the family asked for it.","是否家屬要求。"]], ["A"], "Notification may be correct, but the nurse often needs focused assessment or immediate safety intervention first.", "通知可能正確，但護理師常需先做重點評估或立即安全處理。", ["english_wording","prioritization"]),
  item("E006", "english_wording", "The phrase 'requires immediate intervention' most closely means:", "requires immediate intervention 最接近的意思是：", [["A","Needs action now to prevent harm.","需要現在行動以防傷害。"],["B","Can wait until discharge.","可等到出院。"],["C","Is only a documentation issue.","只是記錄問題。"],["D","Is always psychosocial only.","永遠只是心理社會問題。"]], ["A"], "Immediate intervention means prompt action is needed for safety or clinical risk.", "Immediate intervention 表示因安全或臨床風險需要及時處理。", ["english_wording"]),

  item("OS004", "osce_transition", "Which phrase best explains a pain assessment?", "哪句話最能解釋疼痛評估？", [["A","I need you to pick a number because the form says so.","表格要求，所以你選數字。"],["B","Can you rate your pain from 0 to 10, where 0 is no pain and 10 is the worst pain?","請用 0 到 10 評分你的疼痛，0 是不痛，10 是最嚴重。"],["C","Pain is not important right now.","疼痛現在不重要。"],["D","Your pain score should be low.","你的疼痛分數應該低。"]], ["B"], "The phrase is clear, patient-centered and clinically useful.", "此句清楚、以病人為中心且具臨床用途。", ["osce_transition","therapeutic_communication"]),
  item("OS005", "osce_transition", "Which phrase best shows escalation using objective data?", "哪句話最能用客觀資料做升級通報？", [["A","The client looks bad.","病人看起來不好。"],["B","The family is nervous.","家屬很緊張。"],["C","The blood pressure is 88/54 and the heart rate is 122.","血壓 88/54，心率 122。"],["D","I just feel worried.","我只是覺得擔心。"]], ["C"], "Objective vital-sign data makes escalation clearer and safer.", "客觀生命徵象讓升級通報更清楚且安全。", ["osce_transition","cue_recognition"]),

  item("T004", "test_strategy", "Which approach is best after missing multiple pharmacology questions?", "連續錯多道藥理題後，哪種方法最好？", [["A","Create class-based medication cards.","建立按藥物類別整理的卡片。"],["B","Stop studying pharmacology.","停止學藥理。"],["C","Memorize only one drug name.","只背一個藥名。"],["D","Switch resources every hour.","每小時換資源。"]], ["A"], "Class-based medication cards help organize purpose, risks, monitoring and teaching.", "按類別整理藥卡有助於組織用途、風險、監測與教學。", ["test_strategy","knowledge_gap"]),
  item("T005", "test_strategy", "Which behavior best supports timed-practice improvement?", "哪種行為最能支持限時練習進步？", [["A","Review why each wrong option was tempting.","複盤每個錯誤選項為何有誘惑性。"],["B","Only celebrate the score.","只看分數。"],["C","Skip all questions with long stems.","跳過所有長題幹。"],["D","Translate every word in the final week.","最後一週逐字翻譯每個詞。"]], ["A"], "Understanding distractors improves reasoning and reduces repeat mistakes.", "理解干擾選項能提升推理並減少重複錯誤。", ["test_strategy"]),

  item("MIX004", "mixed_review", "Which client with abdominal pain should be assessed first?", "腹痛病人中哪位應先評估？", [["A","A client with rigid abdomen and hypotension.","腹部僵硬且低血壓的病人。"],["B","A client with mild gas after eating beans.","吃豆後輕微脹氣病人。"],["C","A client asking for antacid refill.","要求補充制酸劑的病人。"],["D","A client with chronic constipation asking about fiber.","慢性便秘病人詢問纖維。"]], ["A"], "Rigid abdomen with hypotension suggests possible acute abdomen/perfusion concern.", "腹部僵硬合併低血壓提示可能急腹症/灌流風險。", ["cue_recognition","prioritization"]),
  item("MIX005", "mixed_review", "Which discharge statement after heart failure teaching requires further teaching?", "心衰出院教學後哪句話表示需要進一步教學？", [["A","I will weigh myself daily.","我會每天量體重。"],["B","I will call if I gain weight suddenly.","如果體重突然增加我會聯絡。"],["C","I can stop my medication when swelling improves.","水腫改善後我可以停藥。"],["D","I will follow the sodium plan.","我會遵守鈉攝入計劃。"]], ["C"], "Stopping medication without provider guidance shows misunderstanding.", "未經指示自行停藥表示理解錯誤。", ["english_wording","knowledge_gap"]),
  item("MIX006", "mixed_review", "Which client with chest discomfort requires immediate assessment?", "胸部不適病人中哪位需要立即評估？", [["A","Chest pressure with sweating and nausea.","胸部壓迫感合併出汗和噁心。"],["B","Brief discomfort after spicy food now resolved.","辛辣食物後短暫不適現已緩解。"],["C","Muscle soreness after exercise yesterday.","昨天運動後肌肉痠痛。"],["D","Requests information about cholesterol.","詢問膽固醇資訊。"]], ["A"], "Chest pressure with diaphoresis and nausea may indicate acute coronary syndrome.", "胸部壓迫感合併出汗和噁心可能提示急性冠脈綜合徵。", ["cue_recognition","prioritization"]),
  item("MIX007", "mixed_review", "Which finding in a client with diabetes requires immediate action?", "糖尿病病人哪個發現需要立即處理？", [["A","Blood glucose 48 mg/dL with confusion.","血糖 48 mg/dL 且混亂。"],["B","Asks about foot care.","詢問足部照護。"],["C","Requests meal plan copy.","要求飲食計劃副本。"],["D","Reports mild thirst after exercise.","運動後輕微口渴。"]], ["A"], "Symptomatic hypoglycemia requires immediate treatment.", "有症狀低血糖需要立即處理。", ["knowledge_gap","prioritization"]),
  item("P011", "prioritization", "A client after hip replacement reports sudden shortness of breath and chest pain. What is priority?", "髖關節置換術後病人突發呼吸困難和胸痛。優先是？", [["A","Assess respiratory status and escalate care.","評估呼吸狀態並升級處理。"],["B","Encourage ambulation.","鼓勵行走。"],["C","Provide routine pain teaching.","提供例行疼痛教學。"],["D","Offer a snack.","提供點心。"]], ["A"], "Postoperative sudden dyspnea and chest pain may suggest pulmonary embolism and require urgent assessment.", "術後突發呼吸困難和胸痛可能提示肺栓塞，需要緊急評估。", ["cue_recognition","prioritization"]),
  item("P012", "prioritization", "A client with a new arteriovenous fistula has no bruit or thrill. What should the nurse do?", "新建動靜脈瘻病人聽不到 bruit、摸不到 thrill。護理師應怎麼做？", [["A","Notify the provider promptly.","及時通知醫師/團隊。"],["B","Take blood pressure on that arm.","在該手臂量血壓。"],["C","Apply tight compression.","施加緊壓。"],["D","Document as expected.","記錄為預期。"]], ["A"], "Absence of bruit/thrill may indicate fistula occlusion and requires prompt follow-up. Protect the fistula arm: do not use it for blood pressure, venepuncture or tight compression.", "bruit/thrill 消失可能提示瘻管阻塞，需要及時追蹤。保護瘻管側手臂：不要在該側量血壓、抽血/穿刺或施加緊壓。", ["knowledge_gap","cue_recognition"]),
  item("PH013", "pharmacology", "A client taking levothyroxine asks when to take it. Which instruction is best?", "服用 levothyroxine 的病人詢問何時服用。哪項指導最好？", [["A","Take it consistently in the morning before breakfast as prescribed.","按處方固定早晨早餐前服用。"],["B","Take it only when tired.","只在疲倦時服用。"],["C","Stop when symptoms improve.","症狀改善後停用。"],["D","Take with all supplements together.","與所有補充劑一起服用。"]], ["A"], "Levothyroxine is typically taken consistently before breakfast; consistency supports absorption and dosing.", "Levothyroxine 通常固定早餐前服用；固定方式有助於吸收與劑量穩定。", ["knowledge_gap"]),
  item("PH014", "pharmacology", "Which finding suggests possible vancomycin infusion reaction?", "哪個發現提示可能 vancomycin 輸注反應？", [["A","Flushing and itching during infusion.","輸注中潮紅與瘙癢。"],["B","Improved appetite.","食慾改善。"],["C","Hair growth.","毛髮增長。"],["D","Clear urine only.","只有尿液清澈。"]], ["A"], "Flushing and itching during vancomycin infusion may indicate infusion reaction and requires follow-up per protocol.", "Vancomycin 輸注中潮紅和瘙癢可能提示輸注反應，需按流程追蹤。", ["knowledge_gap","cue_recognition"]),
  item("S011", "safety_infection", "Which action is best after a needlestick injury?", "針刺傷後哪項行動最佳？", [["A","Wash the area and report according to protocol immediately.","清洗部位並立即按流程報告。"],["B","Ignore it if there is no pain.","無疼痛則忽略。"],["C","Wait until the end of the week.","等到週末。"],["D","Cover it and tell no one.","包紮但不告知。"]], ["A"], "Needlestick injuries require immediate first aid and reporting according to exposure protocol.", "針刺傷需要立即初步處理並按暴露流程報告。", ["safety_infection"]),
  item("S012", "safety_infection", "Which intervention helps prevent pressure injury?", "哪項干預有助於預防壓傷？", [["A","Reposition an immobile client regularly.","定期為不能活動病人翻身。"],["B","Leave moisture on the skin.","讓皮膚保持潮濕。"],["C","Avoid nutrition assessment.","避免營養評估。"],["D","Keep wrinkles under the client.","讓床單皺褶留在身下。"]], ["A"], "Regular repositioning reduces prolonged pressure and pressure-injury risk.", "定期翻身可減少長時間受壓與壓傷風險。", ["safety_infection"]),
  item("MC009", "maternal_child", "Which newborn temperature requires nursing intervention?", "哪個新生兒體溫需要護理處理？", [["A","36.0 C with poor feeding.","36.0 C 且餵食差。"],["B","36.8 C with normal feeding.","36.8 C 且餵食正常。"],["C","37.0 C after skin-to-skin care.","皮膚接觸照護後 37.0 C。"],["D","36.9 C and sleeping calmly.","36.9 C 且安睡。"]], ["A"], "Low temperature with poor feeding may indicate newborn instability and requires intervention.", "低體溫合併餵食差可能提示新生兒不穩定，需要處理。", ["maternal_child","cue_recognition"]),
  item("MC010", "maternal_child", "A parent asks when to seek help for an infant. Which statement indicates understanding?", "家長詢問何時需為嬰兒求助。哪句話表示理解？", [["A","I will seek help if the baby has difficulty breathing.","如果寶寶呼吸困難我會求助。"],["B","I will wait a week if the baby turns blue.","如果寶寶發紫我會等一週。"],["C","Poor feeding is never important.","餵食差永遠不重要。"],["D","Fever in a young infant can always wait.","小嬰兒發燒永遠可以等。"]], ["A"], "Difficulty breathing is an urgent infant warning sign.", "呼吸困難是嬰兒緊急警訊。", ["maternal_child","safety_infection"]),
  item("E007", "english_wording", "The phrase 'no further action is needed' is safest only when:", "no further action is needed 只有在什麼情況下才安全？", [["A","The finding is expected and no safety concern exists.","該發現可預期且無安全風險。"],["B","The option is short.","選項很短。"],["C","The client is upset.","病人不高興。"],["D","The nurse is busy.","護理師很忙。"]], ["A"], "No further action is appropriate only when the finding is expected and safe.", "只有當發現可預期且安全時，才適合不需進一步行動。", ["english_wording","test_strategy"]),
  item("T006", "test_strategy", "Which review method is best for NGN case studies?", "NGN case studies 最佳複習方法是？", [["A","Write the key cues and why they matter.","寫下關鍵線索及其重要性。"],["B","Only memorize the final answer.","只背最終答案。"],["C","Skip long cases.","跳過長病例。"],["D","Read rationales without noting errors.","看解析但不記錯因。"]], ["A"], "NGN improvement depends on cue recognition and reasoning, not answer memorization only.", "NGN 進步取決於線索辨識和推理，而不只是背答案。", ["test_strategy","cue_recognition"]),
  item("OS006", "osce_transition", "Which phrase best asks permission before assessment?", "評估前哪句話最能表達徵求同意？", [["A","I am going to check your wound now; is that okay?","我現在要檢查你的傷口，可以嗎？"],["B","I do not need to explain this.","我不需要解釋。"],["C","You have no choice.","你沒有選擇。"],["D","I will do it quickly without telling you.","我不告訴你，快速做完。"]], ["A"], "Permission and explanation support dignity, consent and OSCE communication.", "徵求同意與解釋有助於尊嚴、同意與 OSCE 溝通。", ["osce_transition","therapeutic_communication"]),
  item("MIX008", "mixed_review", "Which client statement about antibiotics requires further teaching?", "關於抗生素，病人哪句話表示需要進一步教學？", [["A","I will finish the course as prescribed.","我會按處方完成療程。"],["B","I will report rash or breathing difficulty.","若出現皮疹或呼吸困難我會回報。"],["C","I can stop when I feel better after one day.","一天後感覺好轉即可停藥。"],["D","I will ask before taking other medications.","服用其他藥前我會詢問。"]], ["C"], "Stopping antibiotics early can contribute to treatment failure and resistance concerns.", "過早停用抗生素可能導致治療失敗並增加耐藥風險。", ["knowledge_gap","english_wording"])
];

const payload = {
  version: "0.4",
  status: "50 additional original beta items for editorial and nursing review",
  disclaimer: "Independent educational practice items. Not official NCLEX questions and not copied from any commercial QBank.",
  items
};

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `${JSON.stringify(payload, null, 2)}\n`);
console.log(`Wrote ${out}`);
console.log(`Items: ${items.length}`);
