const {pageShell}=require('../site');
const frame=require('./academic-subpage.cjs');
const guide='/zh/countries/canada/schools/',privatePath='/zh/private-school-alliance/canada/',service='/zh/services/canada-school-application/';
const sources={minor:'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/prepare/minor-children.html',cost:'https://www.educanada.ca/programs-programmes/education_cost-cout_education.aspx?lang=eng',tdsb:'https://www.tdsb.on.ca/internationalstudents/Home/Kindergarten-to-Grade-12',tdsbCare:'https://www.tdsb.on.ca/internationalstudents/Home/FAQs',yrdsb:'https://www2.yrdsb.ca/schools-programs/international-student-programs',burnaby:'https://studyinburnaby.ca/',westvan:'https://westvancouverschools.ca/international/future-students/'};
const boards=[
 ['Toronto District School Board（TDSB）','安省・多倫多','幼稚園–G8；G9–12','小學安置按家長／監護人的住址與學位；JK–G8 須與家長或監護人同住。中學選校須查國際生開放名單。',sources.tdsb],
 ['York Region District School Board（YRDSB）','安省・約克區','JK–G12','涵蓋多倫多以北的約克區。比較住址、學校、國際生名額及通勤；特色課程是否接收國際生須另查。',sources.yrdsb],
 ['Burnaby School District','BC 省・本拿比','小學 K–G7；中學 G8–12','小學提供 ELL 英語支援；寄宿家庭資格、陪同要求及入學期按年級確認。',sources.burnaby],
 ['West Vancouver Schools','BC 省・西溫哥華','小學及中學','設國際學生申請渠道。須同步確認學校名額、年級、英語支援及住宿安排。',sources.westvan]
];
const schools=[
 {name:'Upper Canada College',region:'安大略省',city:'Toronto 多倫多',type:'男校｜IB｜走讀及寄宿',grades:'寄宿由 Year 8 起；主要入學年為 Year 9、10、11，不接收 Year 12 新生。',note:'適合把多倫多男校及 IB 列入比較的家庭；低年級走讀與寄宿資格分別確認。',url:'https://www.ucc.on.ca/admission/faq',home:'https://www.ucc.on.ca/',slug:'upper-canada-college'},
 {name:'Appleby College',region:'安大略省',city:'Oakville 奧克維爾',type:'走讀及寄宿',grades:'學校 G7–12；校內寄宿 G9–12。',note:'G7–8 有課程不代表可入住 G9–12 的寄宿部；須另確認低年級居住安排。',url:'https://www.appleby.on.ca/',slug:'appleby-college'},
 {name:'Ridley College',region:'安大略省',city:'St. Catharines 聖凱瑟琳斯',type:'IB｜走讀及寄宿',grades:'學校 JK–G12；目前 Junior Boarding 為 G7–8，Senior Boarding 為 G9–12。',note:'校方已公布 2027/28 寄宿申請入口；實際空位及錄取以校方審核為準。',url:'https://www.ridleycollege.com/admissions/apply',home:'https://www.ridleycollege.com/',slug:'ridley-college'},
 {name:'St. Michaels University School',region:'卑詩省（BC）',city:'Victoria 維多利亞',type:'走讀及寄宿',grades:'學校 JK–G12；寄宿限 G9–12，不提供 G9 以下寄宿。',note:'位於溫哥華島，並非溫哥華市；需把交通與家長探訪安排納入比較。',url:'https://www.smus.ca/admissions/apply-to-boarding/boarding-9-12',home:'https://www.smus.ca/',slug:'st-michaels-university-school'},
 {name:"Bishop’s College School",region:'魁北克省',city:'Sherbrooke 舍布魯克',type:'英語授課｜走讀及寄宿',grades:'G7–12。',note:'學校位於魁北克；法語學習、文憑及省級入學文件須按個案確認。',url:'https://www.bishopscollegeschool.com/',slug:'bishops-college-school'}
];
const link=(url,label)=>`<a href="${url}" target="_blank" rel="noopener">${label} ↗</a>`;
const sec=(title,body)=>`<section><h2>${title}</h2>${body}</section>`;
const table=(head,rows)=>`<div class="ca-table" tabindex="0" role="region" aria-label="${head[0]}比較表"><table><thead><tr>${head.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const contact=`<p><strong>海外督導 OTC｜海圖規劃・留學諮詢</strong><br>WhatsApp：<a href="https://wa.me/447947991572?text=${encodeURIComponent('您好，我想諮詢加拿大中小學留學。孩子目前年級：；預計入學年月：；家長是否陪同：；預算：。')}">+44 7947 991572</a> · <a href="mailto:office@overseasuk.com?subject=${encodeURIComponent('加拿大中小學留學諮詢')}">office@overseasuk.com</a><br>微信：overseasus</p>`;
const fee=`<p>OTC 透過合作代理渠道提供免費入學申請代辦，不另向家庭收取代辦服務費。開始前確認可辦理院校、申請數量及服務範圍；如有招生佣金，由院校或合作渠道按其安排支付，並非家庭另付的代辦費。</p>${table(['項目','安排'],[['免費代辦','選校諮詢、材料清單與整理、申請遞交協調、補件及錄取進度跟進。'],['學校及第三方費用','校方申請費、學費、訂金、保險、翻譯公證、簽證及相關專業人士費用另計。'],['監護與生活支援','當地監護、寄宿家庭、校內住宿、接送及持續學業跟進須另行確認服務提供者、範圍及報價。']])}<p>家庭可先取得各項收費、付款節點與退款條款，再決定是否委託及付款。免費代辦不等於免學費，也不保證錄取或簽證。</p>`;
const care=`<p>IRCC 規定，未滿 17 歲的未成年學生須由父母／法定監護人陪同，或在加拿大安排符合要求的 custodian。17 歲以上仍未成年者，簽證官可按個案要求安排；教育局與學校也可訂定更嚴格條件。${link(sources.minor,'IRCC 未成年學生規定')}</p><div class="ca-columns"><article><h3>家長陪同</h3><p>確認家長可合法停留的身份與期限、孩子學校及通勤、課後接送與醫療保險。孩子獲錄取不等於家長自動取得長期居留或工作權。</p></article><article><h3>孩子在當地就讀</h3><p>監護人、寄宿家庭與寄宿學校的職責可能由不同人承擔。書面確認日常照顧、家校聯絡、醫療同意、緊急聯絡、離校週末及假期住宿。</p></article></div><p>監護文件由誰簽署、誰實際照顧孩子、遇到緊急情況由誰到場，應在接受錄取前確認；寄宿學校的住宿服務不宜直接等同全部監護責任。</p>`;
const process=`<ol><li><strong>需求與選校：</strong>分別整理孩子年級、成績、英語程度、入學年月、家庭預算及陪同安排，確認可申請學校。</li><li><strong>材料與遞交：</strong>依校方清單準備在讀證明、近年成績、護照資料、推薦信及測試／面試；家長核對後遞交。</li><li><strong>錄取與繳費：</strong>核對 offer 的年級、課程、條件、學費、付款期限及退款政策。錄取信、正式 LOA 與繳費的先後順序，按該校書面流程確認。</li><li><strong>入學與行前：</strong>確認所需學簽及省級文件、監護、住宿、保險、抵埗註冊與緊急聯絡安排。</li></ol>`;
const configs={
 guide:{name:'加拿大中小學留學',sub:'公校教育局・私立學校',path:guide,summary:'分開比較公校教育局與私校，了解年級銜接、英語支援、陪讀監護、住宿及申請費用。',image:'canada-schools'},
 private:{name:'私校聯盟｜加拿大',sub:'走讀・寄宿・年級銜接',path:privatePath,summary:'按安大略省、卑詩省及魁北克省查閱私校，分清學校年級與寄宿入學年級。',image:'canada-private-schools'},
 service:{name:'加拿大中小學申請',sub:'免費代辦・監護與住宿協調',path:service,summary:'海圖規劃協助選校、申請及錄取跟進；監護、住宿與持續支援按家庭需要另行確認。',image:'canada-school-application'}
};
function guideBody(){return sec('公校與私校',`<p>加拿大中小學由各省及地區管理。公校通常透過教育局國際學生部申請；私校由校方招生部審核。孩子的入學年級、可選課程與學分銜接須按原有學習紀錄確認，不能只用年齡換算。</p>${table(['比較','公校教育局','私立學校'],[['申請對象','教育局國際學生項目；學校安置受名額與住址等條件影響。','按個別學校申請；可能要求推薦、評估或面試。'],['生活安排','家長／監護人同住或符合規定的寄宿家庭；依年級確認。','走讀、校內寄宿或其他獲批准的住宿；寄宿可有較高入學年級。'],['課程與支援','核對實際開課及 ELL／ESL 支援；特色課程未必向國際生開放。','核對省文憑、IB／AP 等課程及英語支援，不只看學校名稱。']])}`)
+sec('公校教育局',`<p>以下為安省及 BC 省的選校參考，並非全加拿大教育局名單；國際生資格、名額及學校分配以當期招生部確認為準。</p>${table(['教育局','地區','學段','選校重點'],boards.map(b=>[link(b[4],b[0]),b[1],b[2],b[3]]))}<p>TDSB 要求 JK–G8 學生與家長或監護人同住，教育局本身不提供監護人。這是該教育局的規定，不應直接套用到所有地區。${link(sources.tdsbCare,'TDSB 官方常見問題')}</p>`)
+sec('私立學校',`<p>私校按省份及走讀／寄宿方式另列。選校時同時確認學校開設年級及寄宿年級，例如 Appleby 有 G7–8 課程，但校內寄宿為 G9–12；SMUS 也不提供 G9 以下寄宿。</p><div class="ca-columns"><article><h3>安大略省</h3><p>Upper Canada College、Appleby College、Ridley College。</p></article><article><h3>BC 省與魁北克省</h3><p>St. Michaels University School、Bishop’s College School。</p></article></div><a class="btn btn-primary" href="${privatePath}">私校聯盟加拿大區 →</a>`)
+sec('監護與住宿',care)
+sec('費用',`<p>以下為 EduCanada 公布的全國年度參考，以加元 CAD 計；查閱日期為 2026 年 10 月 4 日。不是下列個別學校的報價，也不能用作 2027/28 學年收費承諾。</p>${table(['類型','年度參考','預算範圍'],[['公立中小學','CAD 10,000–17,000','學費參考；住宿、監護與生活費另列。'],['私立走讀學校','CAD 15,000–30,000','學費參考；個別學校可能高於此範圍。'],['私立寄宿學校','CAD 63,000–83,000','校方套餐所含住宿餐食及附加費須逐項確認；並非全部費用上限。']])}<p>${link(sources.cost,'EduCanada 費用來源')}</p><p>家庭預算另列醫療保險、交通、制服設備、活動、假期住宿與應急金。兩名孩子同時申請，應分列各自費用，再計算可共用的家庭支出。</p>`)
+sec('申請材料與流程',process+`<p>初次諮詢可提供匿名的年級、成績概況、英語程度、入學年月、城市偏好、預算及陪同安排；毋須在公開留言提交護照或財務資料。</p>`)
+sec('免費申請服務',`<p>OTC 免費入學申請代辦涵蓋選校諮詢、材料整理與申請跟進；校方、監護住宿及第三方費用另計。</p><a class="btn btn-primary" href="${service}">服務範圍與費用 →</a>${contact}`);
}
function privateBody(){return sec('學校與年級',`<p>以下五所學校按省份陳列，保留走讀及寄宿的不同入學條件。家庭可依孩子年級、英語、課程及生活安排建立候選名單。</p>${[...new Set(schools.map(s=>s.region))].map(region=>`<h3 class="ca-region">${region}</h3><div class="ca-columns">${schools.filter(s=>s.region===region).map(s=>`<article class="ca-school"><h3>${s.name}</h3><p class="ca-label">${s.city}｜${s.type}</p><p><strong>年級：</strong>${s.grades}</p><p>${s.note}</p><p>${link(s.url,'校方招生資料')}${s.home?' · '+link(s.home,'學校網站'):''}</p></article>`).join('')}</div>`).join('')}<p>資料核對：2026 年 10 月 4 日。私校聯盟為 OTC 選校資訊分類，不表示名單內所有學校均已授予 OTC 代理資格；辦理渠道在委託前確認。</p>`)
+sec('選校',`<p>先確認實際入學年級及可選科目，再比較學校支援。寄宿年級不符合時，可另看有相應年級寄宿的學校，或評估家長陪同走讀；不能把同一所學校有小學部，理解為小學生也可以寄宿。</p><p>轉入高中須查學分認定、畢業要求及大學先修科目；IB、AP 與省高中課程的修讀安排應向校方確認。</p>`)
+sec('監護與住宿',care)
+sec('學費與申請',`<p>按學年、入學年級及國際生身份向校方索取正式費用表，分列學費、寄宿、餐食、註冊費、保險、監護與假期費用；獎學金或手足減免須取得書面確認後才計入預算。</p><p><a href="${guide}#topic-4">加拿大中小學費用參考 →</a> · <a href="${guide}#topic-1">公校教育局 →</a></p>${process}<p><a class="btn btn-primary" href="${service}">免費代辦與另付費項目 →</a></p>${contact}`);
}
function serviceBody(){return sec('服務內容',`<div class="ca-columns"><article><h3>選校與申請</h3><p>比較公校教育局與私校的年級、課程、英語支援及地點；確認可辦理學校，整理申請材料，協調遞交、補件及面試。</p></article><article><h3>錄取與入學</h3><p>協助家長閱讀錄取條件、校方收費與退款條款，整理註冊及行前事項。兄弟姊妹分別審核，不預設同校或同時獲錄取。</p></article><article><h3>監護與住宿協調</h3><p>按地點和年齡確認可用的當地服務，協調服務提供者、居住方式、家校聯絡及假期安排；實際人選、職責、到場及緊急支援時段寫入服務約定。</p></article><article><h3>在讀支援</h3><p>如需持續家校溝通、成績跟進、學術輔導或生活支援，另行確認頻率、交付內容與收費。入學代辦不自動包含這些長期服務。</p></article></div>`)
+sec('免費與另付費項目',fee)
+sec('辦理流程',process)
+sec('諮詢資料',`<p>請一次提供孩子目前年級與課程、預計入學年月、英語程度、預算、目標城市，以及家長是否陪同。若有兩名或以上孩子，請分別列出學業資料；初次諮詢毋須提供證件號碼或財務證明。</p>${contact}<p><a href="${guide}">加拿大中小學選校與監護詳解 →</a> · <a href="${privatePath}">私校聯盟加拿大區 →</a></p>`);
}
const css=`<style>.canada-page{background:#fffdf7;color:#213e50}.canada-page .consolidated-page{max-width:1140px;margin:auto;padding:24px;line-height:1.85;font-size:16px}.canada-page .consolidated-page section{padding:24px 0;scroll-margin-top:90px}.canada-page .consolidated-page h2{font-size:26px;color:#14354b;border-top:3px solid #17394d;padding-top:16px;margin-top:0}.canada-page h3{color:#17394d;font-size:20px}.ca-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px 32px}.ca-school{border-top:1px solid #b6c4c5;padding:10px 0}.ca-region{background:#eef1ed;border-left:4px solid #c5a253;padding:10px 16px}.ca-label{font-size:14px;color:#496275}.ca-table{overflow:auto;max-width:100%;margin:18px 0}.ca-table table{border-collapse:collapse;width:100%;min-width:650px}.ca-table th{background:#15394f;color:white;text-align:left}.ca-table td,.ca-table th{border:1px solid #cbd5d7;padding:13px;vertical-align:top}.ca-table td:first-child{min-width:170px}.ca-table tbody tr:nth-child(even){background:#eff3f1}.canada-page .ca-table a{color:#184d66;text-decoration:underline}.canada-page .services-hero h1{font-size:clamp(30px,3.5vw,48px)}.canada-page .services-hero h2{font-size:21px}.canada-page figure{max-width:600px;margin:30px 0}.canada-page figure img{width:100%;height:auto}.canada-page figcaption,.ca-note{font-size:13px;color:#516772}.canada-page .service-hero-layout{grid-template-columns:minmax(0,1fr) minmax(0,1.2fr);gap:30px}.canada-page .service-hero-panel a{min-height:180px;padding:20px 14px}.canada-page .service-hero-panel a::before,.canada-page .service-review-strip a::before{display:none}.canada-page .service-hero-panel{min-width:0}.canada-page .service-hero-panel strong{font-size:18px}.canada-page .service-hero-layout>div{min-width:0}.canada-page li{margin-bottom:10px}@media(max-width:900px){.canada-page .service-hero-layout{grid-template-columns:1fr}}@media(max-width:700px){.ca-columns{grid-template-columns:1fr;gap:4px}.canada-page .consolidated-page{padding:20px 16px}.canada-page .service-hero-panel,.canada-page .service-review-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.canada-page .services-hero h1{font-size:30px}}</style>`;
function meta(kind){const c=configs[kind];return {path:c.path,titleZh:c.name+'｜海外督導 OTC',summaryZh:c.summary,shareImageZh:'/assets/social/'+c.image+'-20261004-v1.png',socialImageVersion:'v=20261004-1',socialImageWidth:1200,socialImageHeight:630};}
function render(kind){const c=configs[kind],m=meta(kind),cover=m.shareImageZh+'?'+m.socialImageVersion;let body=({guide:guideBody,private:privateBody,service:serviceBody}[kind])();body=`<nav aria-label="相關頁面"><a href="/zh/countries/canada/">加拿大留學</a> · <a href="${guide}">中小學</a> · <a href="${privatePath}">私校聯盟</a> · <a href="${service}">申請服務</a></nav><p class="ca-note">資料核對：2026 年 10 月 4 日｜海圖規劃・留學諮詢</p>`+body+`<figure><img src="${cover}" width="1200" height="630" alt="${c.name}：${c.sub}" loading="lazy"><figcaption>${c.name}｜海外督導 OTC</figcaption></figure><p class="ca-note">學校資料及規則以相關政府、教育局與校方當期公布為準。簽證與個人移民法律事項由合資格專業人士處理。</p>`;
let framed=frame(c.name,body).replace('<h2>教育服務與雙語學習</h2>',`<h2>${c.sub}</h2>`).replace('按主題查閱服務、課程與出版資料，了解內容與聯絡方式。',c.summary).replace('<a class="btn btn-secondary" href="/zh/site-directory/">全站目錄</a>',`<a class="btn btn-secondary" href="${guide}">中小學總覽</a>`);
framed=framed.replace(/<section class="band service-review-strip">[\s\S]*?<\/section>/,`<nav class="band service-review-strip" aria-label="加拿大留學分類"><a href="${guide}#topic-1"><b>PUBLIC</b><strong>公校教育局</strong><span>安省・BC 省</span></a><a href="${privatePath}"><b>PRIVATE</b><strong>私校聯盟</strong><span>走讀與寄宿</span></a><a href="${guide}#topic-3"><b>CARE</b><strong>監護與住宿</strong><span>照顧安排及責任</span></a><a href="${service}"><b>APPLY</b><strong>免費代辦</strong><span>服務與另付費項目</span></a></nav>`);
return pageShell({title:m.titleZh,path:c.path,lang:'zh-Hant',locale:'zh',current:'services',bodyClass:'canada-page',description:c.summary,image:cover,imageWidth:1200,imageHeight:630,imageAlt:c.name,body:css+framed});}
module.exports={guide,privatePath,service,configs,meta,render,boards,schools,sources};
