const {pageShell}=require('../site');
const art='/zh/services/art-portfolio-coaching/';
module.exports=()=>pageShell({title:'海外督導 OTC｜留學申請・專業陪跑・雙語學習',path:'/',alternatePath:'/en/',current:'home',locale:'zh',lang:'zh-Hant',description:'海外督導 OTC 中文官網。按需求查閱留學申請、藝術與設計作品集、課程輔導、寒暑校、海外生活及雙語出版，了解服務流程與費用。',body:`
<style>.otc-home{--ink:#173447;--muted:#53686e;color:var(--ink)}.otc-home .home-wrap{width:min(1120px,calc(100% - 40px));margin:auto}.otc-home .home-intro{background:#163347;color:#fff;padding:54px 0 42px}.otc-home h1{font-size:44px;line-height:1.25;margin:10px 0 18px;letter-spacing:.03em}.otc-home .home-intro p{max-width:650px;line-height:1.9;color:#e6eeeb}.otc-home .home-kicker{font-size:14px;letter-spacing:.08em}.otc-home .home-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:25px}.otc-home .home-actions a{padding:11px 18px;background:#eff3ec;color:#173447;text-decoration:none;border-radius:2px}.otc-home .home-actions a+ a{background:transparent;border:1px solid #9cb2b9;color:#fff}.otc-home .home-section{padding:36px 0}.otc-home h2{font-size:26px;margin:0 0 18px}.otc-home h3{font-size:21px;margin:0 0 10px}.otc-home p{line-height:1.85}.otc-home .home-groups{display:grid;grid-template-columns:1fr 1fr;gap:0 34px}.otc-home .home-group{border-top:1px solid #bac8c8;padding:25px 0}.otc-home .home-group p{color:var(--muted);margin:0 0 12px}.otc-home .home-links{display:flex;flex-wrap:wrap;gap:8px 20px}.otc-home a{color:var(--ink);text-underline-offset:4px}.otc-home .home-feature{background:#eaf0ed;padding:28px;border-left:4px solid #557e75}.otc-home .home-category{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.otc-home .home-category a{padding:12px 0;border-bottom:1px solid #b9cac5}.otc-home .home-country{display:flex;flex-wrap:wrap;gap:12px 24px}.otc-home .home-contacts{border-top:1px solid #bac8c8;padding:30px 0;display:grid;grid-template-columns:1.4fr 1fr;gap:24px}.otc-home .home-institutional{font-size:14px;color:var(--muted);padding:18px 0;border-top:1px solid #d3dcda}.otc-home .home-institutional a{margin-right:20px}.site-header .nav .brand small{letter-spacing:.05em}.site-header .nav-links .language-link{font-size:12px;font-weight:400;opacity:.8}.site-header .nav{max-width:1200px}.site-header .nav-links{flex-wrap:wrap}@media(max-width:680px){.otc-home h1{font-size:34px}.otc-home .home-intro{padding:32px 0}.otc-home .home-groups,.otc-home .home-contacts{grid-template-columns:1fr}.otc-home .home-category{grid-template-columns:1fr 1fr}.otc-home .home-feature{padding:20px}.otc-home .home-wrap{width:calc(100% - 32px)}}
</style><main class="otc-home">
<section class="home-intro"><div class="home-wrap"><div class="home-kicker">海外督導 OTC · 英國倫敦</div><h1>留學申請與專業陪跑</h1><p>為華語學生與家庭提供選校、申請、作品集與學習支援。從目前的背景和目標出發，了解流程、費用及每一步的準備。</p><div class="home-actions"><a href="#services">查看服務</a><a href="https://wa.me/447947991572">WhatsApp 諮詢</a></div></div></section>
<section id="services" class="home-section"><div class="home-wrap"><h2>服務分類</h2><div class="home-groups">
<section class="home-group"><h3>01 升學與申請</h3><p>選校、入學要求、申請文件、轉學及升學路線。</p><div class="home-links"><a href="/zh/services/">升學服務</a><a href="/zh/asso-hd-university-progression/">Asso／HD 升大學</a><a href="/zh/services/personal-statement-support/">申請文書</a><a href="/zh/study-group-2026-applications/">大學預科與銜接</a></div></section>
<section class="home-group"><h3>02 藝術與設計</h3><p>按專業整理作品集要求、創作流程、階段成果與總審。</p><div class="home-links"><a href="${art}">設計申請｜藝術總監</a><a href="${art}#disciplines">八類專業</a><a href="${art}#fees">陪跑收費</a></div></section>
<section class="home-group"><h3>03 課程與學習</h3><p>國際課程、英語、學業規劃及學習工具。</p><div class="home-links"><a href="/international-curriculum-tutoring/">國際課程輔導</a><a href="/zh/services/business-english-study-support/">商業英語陪跑</a><a href="/zh/othm-qualifications/">OTHM 課程</a><a href="/zh/study-planning/">學業規劃</a><a href="/apps/">學習工具</a></div></section>
<section class="home-group"><h3>04 寒暑校與中小學</h3><p>按年齡、國家、課程、住宿及預算比較學校與活動。</p><div class="home-links"><a href="/zh/summer-school-alliance/">寒暑校</a><a href="/zh/private-school-alliance/">私立學校</a><a href="/zh/language-school-alliance/">語言學校</a><a href="/zh/us-high-school-exchange-support/">美國高中交換</a></div></section>
<section class="home-group"><h3>05 海外生活與發展</h3><p>求職準備、海外生活、簽證資料及後續服務。</p><div class="home-links"><a href="/zh/australia-job-search-coaching/">求職陪跑</a><a href="/zh/france-study-work-settlement-support/">法國留學與生活</a><a href="/zh/immigration-info/">移居資訊</a><a href="/zh/services/">生活與文件服務</a></div></section>
<section class="home-group"><h3>06 導報與出版</h3><p>留學資訊、雙語學習書籍及出版資源。</p><div class="home-links"><a href="/zh/insights/">留學導報</a><a href="/zh/publishing/">海外出版</a><a href="/study-guides/">學習書籍</a><a href="/search/">搜尋全站</a></div></section>
</div></div></section>
<section class="home-section"><div class="home-wrap"><div class="home-feature"><h2>設計申請｜藝術總監</h2><p>按專業查看作品集陪跑，從選題、研究、階段評閱到整本總審。每一門類分開說明，收費與委託範圍集中查閱。</p><nav class="home-category" aria-label="藝術與設計門類"><a href="${art}#illustration">插畫 →</a><a href="${art}#graphic-design">平面與視覺傳達 →</a><a href="${art}#product-design">產品與工業設計 →</a><a href="${art}#animation">動畫與角色設計 →</a><a href="${art}#fashion">服裝與紡織設計 →</a><a href="${art}#spatial-design">空間與建築設計 →</a><a href="${art}#fine-art">純藝術 →</a><a href="${art}#photography-film">攝影與影像 →</a></nav><a href="${art}#fees">查看流程、成果與收費 →</a></div></div></section>
<section class="home-section"><div class="home-wrap"><h2>國家與地區</h2><nav class="home-country" aria-label="留學地區"><a href="/zh/study-group-2026-applications/">英國升學</a><a href="/zh/australia-vet-tafe-pathways/">澳洲職業教育</a><a href="/zh/countries/canada/">加拿大</a><a href="/zh/countries/hong-kong/">香港</a><a href="/zh/countries/south-korea/">韓國</a><a href="/zh/countries/nordic/">北歐</a><a href="/zh/thailand-university-study/">泰國</a><a href="/zh/services/">其他地區與服務 →</a></nav></div></section>
<section id="contact"><div class="home-wrap"><div class="home-contacts"><div><h2>聯絡海外督導</h2><p>說明目前學歷、希望申請的專業或服務，以及計畫時間。未決定學校，也可以先諮詢。</p><a href="https://wa.me/447947991572">WhatsApp +44 7947 991572 →</a></div><div><p><a href="mailto:office@overseasuk.com">office@overseasuk.com</a><br>微信：overseasus<br>3/F Overseas Education, 207 Regent Street,<br>London W1B 3HH</p><a href="/application-service-standards/">服務準則</a> · <a href="/about/">關於 OTC</a></div></div><div class="home-institutional"><a href="/en/" lang="en">English — Institutional information</a><a href="/zh/education-partners/">教育合作</a><a href="/university-partnerships/">院校合作</a><a href="/client-portal/">客戶端口</a></div></div></section>
</main>`});
