const {pageShell}=require('../site'), frame=require('./academic-subpage.cjs');
module.exports=a=>{
 const cover=a.shareImageZh+'?'+a.socialImageVersion;
 const refs=a.sources.map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener">${n} ↗</a>`).join(' · ');
 const body=a.bodyHtml+`<section><h2>官方資料</h2><p>${refs}</p><p>資料核查：2026 年 10 月 10 日。招生與許可按申請時的院校及主管機關規定；錄取、簽證與認證結果由相應機構決定。</p><figure><img src="${cover}" width="1200" height="630" alt="${a.name}｜海外督導 OTC"><figcaption>${a.name}</figcaption></figure></section>`;
 const css=`<style>.greece-page .consolidated-page{max-width:1040px;margin:auto;padding:24px;font-size:16px;line-height:1.85}.greece-page .services-hero h1{font-size:2.3rem;line-height:1.4}.greece-page .services-hero h2{font-size:1.25rem}.greece-page .service-hero-panel a{min-height:80px;padding:18px!important}.greece-page section{scroll-margin-top:100px}.greece-page .consolidated-page section{padding:16px 0;border-bottom:1px solid #d8d6cc}.greece-page .consolidated-page h2{font-size:1.5rem;border-top:3px solid #173649;padding-top:12px;color:#173649}.greece-page h3{font-size:1.15rem}.greece-columns{display:grid;grid-template-columns:1fr 1fr;gap:28px}.greece-table{overflow-x:auto}.greece-table table{width:100%;min-width:550px;border-collapse:collapse}.greece-table th,.greece-table td{padding:12px;text-align:left;vertical-align:top;border-bottom:1px solid #d8d6cc}.greece-table thead{background:#edf1f3}.greece-page figure{max-width:600px;margin:22px 0}.greece-page figure img{width:100%;height:auto}.greece-page a{overflow-wrap:anywhere}.greece-page li{margin:8px 0}@media(max-width:700px){.greece-columns{grid-template-columns:1fr;gap:0}.greece-page .consolidated-page{padding:18px 16px}.greece-page .service-hero-panel{grid-template-columns:1fr 1fr}.greece-page .services-hero h1{font-size:1.8rem}}</style>`;
 let content=frame(a.name,body).replace('<h2>教育服務與雙語學習</h2>','<h2>課程 · 申請 · 留學生活</h2>').replace('按主題查閱服務、課程與出版資料，了解內容與聯絡方式。',a.summaryZh).replace('海外督導 OTC｜海圖規劃・留學諮詢','海外督導 OTC｜學生服務部');
 return pageShell({title:a.titleZh,path:a.path,lang:'zh-Hant',locale:'zh',description:a.summaryZh,image:cover,imageWidth:1200,imageHeight:630,imageAlt:a.name,bodyClass:'greece-page',body:css+content});
};
