const {pageShell}=require('../site');
const route='/zh/thailand-university-study/';
const title='泰國大學留學・免費申請辦理｜海外督導 OTC';
const description='海外督導與泰國工商大學多年合作，提供免費選校諮詢與申請辦理。了解英語授課選擇、全程預算、文件準備及服務範圍。';
const card=`<section class="band compact-band" id="thailand-study-service"><div class="section-head"><div class="eyebrow">THAILAND · UNIVERSITY STUDY</div><h2>🇹🇭 泰國大學留學｜免費申請辦理</h2><p>英語授課選擇、學費與生活費規劃、選校及申請協助。海外督導與泰國工商大學已有多年合作。</p><a class="btn btn-primary" href="${route}">查看泰國留學服務 →</a></div></section>`;
function addLink(html){if(html.includes('id="thailand-study-service"'))return html;return html.includes('</main>')?html.replace('</main>',card+'</main>'):html.replace('<footer',card+'<footer');}
function render(){return pageShell({title,description,path:route,lang:'zh-Hant',locale:'zh',current:'services',body:`
<style>.thai-study{max-width:1120px;margin:auto;padding:36px 24px 64px;font-size:17px;line-height:1.85;color:#172c40}.thai-study h1{font-size:clamp(30px,5vw,48px);line-height:1.3}.thai-study h2{font-size:26px;margin-top:32px;padding-bottom:10px;border-bottom:1px solid #cbd2d9}.thai-study h3{font-size:20px}.thai-study .thai-hero{border-top:5px solid #172c40;padding:24px 0;border-bottom:1px solid #cbd2d9}.thai-study .service-herald-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(240px,1fr);gap:40px;margin-top:28px}.thai-study aside{background:#f1f3f5;padding:24px;align-self:start}.thai-study .thai-actions{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0}.thai-study .thai-actions a{padding:10px 16px;background:#172c40;color:white;text-decoration:none}.thai-study table{width:100%;border-collapse:collapse}.thai-study th,.thai-study td{text-align:left;padding:12px 8px;border-bottom:1px solid #cbd2d9;vertical-align:top}.thai-study details{padding:15px 0;border-bottom:1px solid #cbd2d9}.thai-study summary{cursor:pointer;font-weight:bold}.thai-study a{overflow-wrap:anywhere}.thai-study .thai-index{display:flex;flex-wrap:wrap;gap:18px;border-bottom:1px solid #cbd2d9;padding:16px 0}@media(max-width:760px){.thai-study{padding:24px 18px}.thai-study .service-herald-grid{grid-template-columns:1fr;gap:16px}}</style>
<main class="thai-study"><nav aria-label="麵包屑"><a href="/zh/">首頁</a> / <a href="/countries/thailand/">泰國留學</a> / 大學申請</nav>
<header class="thai-hero"><div class="eyebrow">THAILAND · OVERSEAS TUTORIAL CENTRE</div><h1>🇹🇭 泰國大學留學<br>免費選校諮詢與申請辦理</h1><p>想在泰國讀大學，也希望兼顧英語學習與留學預算？從你的專業興趣、學歷和家庭預算出發，比較合適課程，再安排申請。</p><p><strong>海外督導與泰國工商大學已有多年合作。</strong>我們協助選校、準備材料、遞交申請及跟進進度。</p><div class="thai-actions"><a href="https://wa.me/447947991572?text=${encodeURIComponent('您好，我想了解泰國大學免費申請服務。')}">WhatsApp 免費諮詢</a><a href="mailto:office@overseasuk.com?subject=${encodeURIComponent('泰國大學留學諮詢')}">電郵了解方案</a></div><p>免費指 OTC 的選校諮詢及申請辦理服務費；學校及第三方收費另付。</p></header>
<nav class="thai-index" aria-label="本頁目錄"><a href="#courses">授課與專業</a><a href="#budget">費用與預算</a><a href="#steps">申請步驟</a><a href="#questions">常見問題</a></nav>
<div class="service-herald-grid"><div class="service-herald-main">
<section id="courses"><h2>先選專業，再確認授課語言</h2><p>泰國有英語授課的國際課程，但不是所有大學、所有專業都用英語。選校時應逐項確認課程語言、英語入學要求、課程內容和實習安排。</p><ul><li>你希望讀本科、碩士，還是先讀語言課程？</li><li>目標專業與未來工作方向是否一致？</li><li>現有學歷及英語成績能否符合所選課程要求？</li><li>若畢業後回原居地升學或就業，學歷認可或專業資格有哪些要求？</li></ul><p>我們按具體院校和課程核對以上資料，不把某個課程的條件當成全泰國通用要求。</p></section>
<section id="budget"><h2>免費辦理，費用仍要算清楚</h2><table><thead><tr><th scope="col">項目</th><th scope="col">如何安排</th></tr></thead><tbody><tr><th scope="row">OTC 選校及申請服務</th><td>免費諮詢、課程比較、材料清單、申請協調及一般進度跟進。</td></tr><tr><th scope="row">院校費用</th><td>申請費、學費、註冊費及其他必繳費，以學校正式費用表為準。</td></tr><tr><th scope="row">生活與出行</th><td>住宿、押金、餐飲、交通、機票及保險，按城市與生活方式估算。</td></tr><tr><th scope="row">第三方項目</th><td>英語考試、翻譯認證、簽證等如有需要，按實際另付。</td></tr></tbody></table><p>如果你的重點是降低留學成本，我們會一起比較「整個學位」的支出，而不只看首年學費。任何獎學金、學分抵免或學費優惠，都需取得院校確認後才納入預算。</p></section>
<section id="steps"><h2>從諮詢到入學的四步</h2><ol><li><strong>了解背景：</strong>告訴我們目前學歷、想讀的科目、入學年份、英語程度及預算。</li><li><strong>比較課程：</strong>確認授課語言、入學要求、總費用、修讀年限及申請日期。</li><li><strong>準備與遞交：</strong>按照院校清單整理材料，經你確認後協助申請。</li><li><strong>跟進及行前準備：</strong>核對錄取條件、付款期限、退款規定、住宿及入學文件。</li></ol><p>通常需要學歷與成績資料；履歷、推薦信、作品集或其他材料則視課程要求提供。初次諮詢只需背景概要，無需在公開留言上傳證件。</p></section>
<section id="questions"><h2>常見問題</h2><details><summary>英語不夠，可以先申請嗎？</summary><p>要看目標課程是否接受後補語言成績、條件錄取或語言銜接。先提供目前程度，我們再向院校確認適用安排。</p></details><details><summary>只能申請泰國工商大學嗎？</summary><p>我們與泰國工商大學已有多年合作，也可按你的需求了解其他院校。其他院校的申請途徑及可辦理範圍會在個案中確認。</p></details><details><summary>免費是否包括學费或簽證？</summary><p>不包括。免費的是 OTC 的選校諮詢及申請辦理；學校、政府及其他第三方收費須另外支付。</p></details><details><summary>申請後一定會錄取嗎？</summary><p>錄取由院校根據申請資料及課程要求決定；簽證由相關主管機關審核。我們協助準備與跟進，不承諾結果。</p></details></section>
</div><aside class="service-guide-side"><h2>開始諮詢</h2><p>請準備五項概要：</p><ol><li>目前學歷及就讀年級</li><li>目標學位與專業</li><li>希望入學年月</li><li>英語程度或成績</li><li>每年或全程預算與幣別</li></ol><p><a href="mailto:office@overseasuk.com">office@overseasuk.com</a><br><a href="https://wa.me/447947991572">WhatsApp +44 7947 991572</a><br>微信：overseasus</p><h3>短期體驗與大學升學</h3><p>如果你仍在探索，也可先了解假期課程，分開比較短期體驗與完整學位的目的及成本。</p><p><a href="/zh/summer-school-alliance/thailand/">泰國假期與遊學項目 →</a></p><h3>官方課程資訊</h3><p><a href="https://www2.rsu.ac.th/faculty/International-College">蘭實大學國際學院</a><br><a href="https://www.bu.ac.th/en/international-programs">曼谷大學國際課程</a></p><p>以上為課程查詢入口；列出院校不表示已取得其招生代理授權。</p><p>服務資訊更新：2026年9月19日</p></aside></div></main>`});}
module.exports={route,title,description,card,addLink,render};
