const { pageShell } = require('../site');
const route = 'zh/services/vietnam-visa';
const card = `<section class="band compact-band"><h2>越南簽證代辦</h2><p>海外督導提供越南簽證申請協助：需求確認、文件檢查、申請協調與進度跟進。</p><a class="button" href="/zh/services/vietnam-visa/">查看服務與諮詢清單 →</a></section>`;
function render() {
return pageShell({title:'越南簽證代辦 | 海外督導 OTC',description:'海外督導提供越南簽證代辦服務，協助需求確認、文件檢查、申請協調與進度跟進。查看費用說明、準備清單及諮詢方式。',path:'/'+route+'/',lang:'zh-Hant',locale:'zh',current:'services',body:`
<style>.vn-visa{max-width:1080px;margin:auto;padding:40px 24px 64px;color:#152f40;font-size:17px;line-height:1.8}.vn-hero{border-top:5px solid #183f50;border-bottom:1px solid #a9bac2;padding:30px 0}.vn-hero h1{font-size:clamp(32px,5vw,54px);line-height:1.25;margin:12px 0}.vn-kicker{font-size:14px;letter-spacing:.08em}.vn-grid{display:grid;grid-template-columns:2fr 1fr;gap:40px;margin-top:32px}.vn-visa h2{font-size:25px;margin-top:30px;border-bottom:1px solid #c3cfd3;padding-bottom:10px}.vn-side{background:#edf3f6;padding:24px;align-self:start}.vn-cta{display:inline-block;background:#183f50;color:white!important;padding:10px 20px;margin:8px 8px 8px 0;text-decoration:none}.vn-visa table{width:100%;border-collapse:collapse}.vn-visa th,.vn-visa td{padding:12px;text-align:left;border-bottom:1px solid #c3cfd3}.vn-visa a{overflow-wrap:anywhere}.vn-visa details{border-bottom:1px solid #c3cfd3;padding:16px 0}.vn-visa summary{cursor:pointer;font-weight:bold}@media(max-width:700px){.vn-grid{grid-template-columns:1fr;gap:16px}.vn-visa{padding:24px 18px}.vn-visa th,.vn-visa td{padding:8px}}</style>
<main class="vn-visa"><nav aria-label="麵包屑"><a href="/zh/services/">服務導覽</a> / 越南簽證代辦</nav>
<header class="vn-hero"><div class="vn-kicker">VIETNAM · VISA APPLICATION SUPPORT</div><h1>越南簽證代辦</h1><p>海外督導 Overseas Tutorial Centre（OTC）提供越南簽證代辦服務，從出行需求、文件準備到申請協調及進度跟進，協助你把每一步安排清楚。</p><a class="vn-cta" href="mailto:office@overseasuk.com?subject=越南簽證代辦諮詢">電郵諮詢</a><a class="vn-cta" href="https://wa.me/447947991572?text=您好，我想諮詢越南簽證代辦。">WhatsApp 諮詢</a></header>
<div class="vn-grid"><div><section><h2>我們協助哪些事項？</h2><ol><li><strong>確認需求：</strong>了解護照國家／地區、入境目的、停留日期與入境次數，核對適合的申請方向。</li><li><strong>文件檢查：</strong>按個案提供清單，協助檢查申請資料、照片及行程資訊是否一致。</li><li><strong>申請協調：</strong>在你確認服務範圍、報價與授權後，協助辦理及需要的承辦對接。</li><li><strong>進度跟進：</strong>協助查看申請狀態、傳達補件要求，取得結果後提醒核對姓名、護照號碼、效期及入境次數。</li></ol><p>旅遊及商務需求請分別說明；工作、就業、長期居留或其他特殊用途另作評估，服務範圍以書面確認為準。</p></section>
<section><h2>費用清楚列明</h2><table><thead><tr><th>項目</th><th>說明</th></tr></thead><tbody><tr><td>官方電子簽證費</td><td>單次入境 US$25；多次入境 US$50。</td></tr><tr><td>OTC 代辦服務費</td><td>按人數、需求與資料情況另行書面報價。</td></tr><tr><td>其他費用</td><td>如涉及加急協調、翻譯或額外服務，先說明可行性、費用及條件，經確認後安排。</td></tr></tbody></table><p>官方電子簽證最長可達90天，單次或多次入境；實際效期以核發結果為準。以上官方資料於2026年9月14日核對，申請時以<a href="https://evisa.gov.vn/">越南官方電子簽證平台</a>最新公布為準。代辦服務費不包含在官方費用內；官方及服務費的取消／退款條件將分開說明。</p></section>
<section><h2>辦理流程</h2><p><strong>提交基本需求 → 核對申請方向 → 確認書面報價及服務條款 → 提交文件與授權 → 申請及補件跟進 → 核對結果。</strong></p><p>若已自行申請，請先說明提交日期、目前狀態及是否收到補件通知，方便評估後續協助。出發時間較近的個案，請先提供確切日期；能否承接及處理時間需確認，不承諾固定日期出簽或保證獲批。</p></section>
<section><h2>常見問題</h2><details><summary>一定要透過代辦嗎？</summary><p>你也可以使用越南官方平台自行申請。OTC 提供的是文件與流程協助，適合希望由專人協調或需要中文溝通的申請人。</p></details><details><summary>是否適用免費留學代辦？</summary><p>越南簽證代辦是獨立服務，費用按書面報價確認，不等同免費留學申請代辦。</p></details><details><summary>可以保證簽證或入境嗎？</summary><p>OTC 並非簽證核發機關。簽證結果及入境決定由相關主管機關作出；我們提供申請協助及進度跟進。</p></details><details><summary>第一次諮詢要傳護照嗎？</summary><p>先提供右列基本需求即可，不需在公開留言或初次諮詢傳證件照片。確認承接後，再按清單與指定方式提供必要文件。</p></details></section>
<section><h2>官方資料</h2><p><a href="https://evisa.gov.vn/">越南國家電子簽證系統</a> · <a href="https://immigration.gov.vn/">越南出入境管理局</a></p></section></div>
<aside class="vn-side"><h2>諮詢前準備</h2><ul><li>護照國家／地區及目前所在地</li><li>預計入境與離境日期</li><li>申請人數</li><li>旅遊、商務或其他用途</li><li>單次或多次進出</li><li>預計入境機場／口岸</li><li>是否已提交申請</li></ul><p>不用公開證件號碼或護照照片。</p><a class="vn-cta" href="mailto:office@overseasuk.com?subject=越南簽證代辦諮詢">開始諮詢</a><p>電郵：<a href="mailto:office@overseasuk.com">office@overseasuk.com</a><br>WhatsApp：<a href="https://wa.me/447947991572">+44 7947 991572</a></p><p>主旨請註明「越南簽證代辦」，並附預計出發日期。</p></aside></div></main>`});
}
module.exports={route,card,render};
