import {validateSource,validateDiagnosis,renderHTML,prompt} from './core.js';
const $=s=>document.querySelector(s);let source,draft,review;let outputs=[];function clearOutputs(){outputs.forEach(URL.revokeObjectURL);outputs=[];document.querySelector('#result').replaceChildren();}const status=t=>$('#status').textContent=t;
const reset=()=>{clearOutputs();draft=review=null;$('#draft').value=$('#final').value='';$('#review').disabled=$('#export').disabled=true;};
async function read(file){if(!file||file.size>150000)throw Error('請選擇 150 KB 以下的 JSON。');return JSON.parse(await file.text());}
function download(name,text,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}
$('#source').onchange=async e=>{source=null;reset();$('#prepare').disabled=true;try{source=validateSource(await read(e.target.files[0]));$('#prepare').disabled=false;status('原始報告格式通過。寫作 '+source.writing.filter(x=>x.response.trim()).length+'/2；可下載初評工作單。');}catch(e){status(e.message);}};
$('#prepare').onclick=()=>download('OTC-01-initial-review.txt',prompt(source));
$('#draft').onchange=async e=>{clearOutputs();draft=review=null;$('#review').disabled=$('#export').disabled=true;$('#final').value='';try{if(!source)throw Error('先匯入原始資料');draft=validateDiagnosis(await read(e.target.files[0]),source,['','']);$('#review').disabled=false;status('初評引文對照通過，可下載複核工作單。');}catch(e){status(e.message);}};
$('#review').onclick=()=>download('OTC-02-cross-check.txt',prompt(source,draft));
$('#final').onchange=async e=>{clearOutputs();review=null;$('#export').disabled=true;try{if(!draft)throw Error('先匯入初評，再完成複核');const value=await read(e.target.files[0]);validateDiagnosis(value.report,source,['','']);if(!Array.isArray(value.changes)||!value.changes.every(x=>typeof x==='string'))throw Error('缺少複核紀錄 changes');review=value;$('#export').disabled=false;status('複核內容及引文檢查通過，可以匯出診斷書。');}catch(e){status(e.message);}};
$('#export').onclick=async()=>{const now=new Date().toISOString();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(source))))).map(x=>x.toString(16).padStart(2,'0')).join('');const r={title:'系統診斷報告',id:crypto.randomUUID(),createdAt:now,sourceHash:hash,method:'外部系統初評與複核 → 匯入 → 格式與引文檢查',engine:'ChatGPT 工作流程（匯入內容）',source,transcripts:['',''],audioProvided:[false,false],diagnosis:review.report,audit:[{stage:'複核內容匯入',at:now,detail:review.changes.join('；')},{stage:'程式引文檢查',at:now,detail:'逐項引用對照通過；無音訊，不作聲學評閱。'}]};clearOutputs();const html=renderHTML(r);for(const [name,text,type] of [['OTC-system-diagnostic.html',html,'text/html'],['OTC-system-diagnostic.json',JSON.stringify(r,null,2),'application/json']]){const u=URL.createObjectURL(new Blob([text],{type}));outputs.push(u);const a=document.createElement('a');a.href=u;a.download=name;a.textContent='下載 '+name;a.style.display='block';$('#result').append(a);}const frame=document.createElement('iframe');frame.title='診斷報告預覽';frame.setAttribute('sandbox','');frame.srcdoc=html;frame.style='width:100%;height:850px;border:1px solid #c8b99b;margin-top:20px';$('#result').append(frame);status('診斷書已產生，可分別下載 HTML 和 JSON；下方可預覽。');};
