import {emptyState,validateState,validProfile,generatePlan,dateKey,addDays,isDate,uid,SKILLS,setCompletion,remaining,stats} from './core.mjs';
const KEY='otc.study-companion.v1';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const longDate=d=>new Date(d+'T12:00:00').toLocaleDateString('zh-Hant',{month:'long',day:'numeric',weekday:'long'});
let state=emptyState(),view='today',selectedDay=dateKey(),weekStart=dateKey(),storageCorrupt=false,today=dateKey(),toastTimeout;
try{const raw=localStorage.getItem(KEY);if(raw)state=validateState(JSON.parse(raw));}catch(e){storageCorrupt=true;warn('無法讀取此裝置的記錄，現有資料未被覆蓋。可到「目標與資料」匯入備份，或確認後清除本機資料。')}
function warn(message){$('storage-warning').hidden=false;$('storage-warning').textContent=message;$('save-status').textContent='儲存需要處理'}
function save(){if(storageCorrupt){warn('目前變更只保留在本次開啟期間，請匯出備份。修復原有資料後再繼續使用。');return false}try{localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='已儲存在此裝置';$('storage-warning').hidden=true;return true}catch(e){warn('此瀏覽器無法儲存記錄。請匯出備份，避免關閉後遺失。');return false}}
function toast(message){clearTimeout(toastTimeout);$('toast').textContent=message;$('toast').classList.add('visible');toastTimeout=setTimeout(()=>$('toast').classList.remove('visible'),4500)}
function navigate(next){view=next;render();$('main').focus();window.scrollTo({top:0,behavior:'instant'})}
const button=(text,action,cls='secondary',attrs='')=>`<button type="button" class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const field=(label,content,hint='')=>`<div class="field"><label>${label}${content}</label>${hint?`<small>${hint}</small>`:''}</div>`;
const options=(items,value)=>items.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x)}</option>`).join('');
function profileForm(isNew){const p=state.profile||{name:'',course:'IELTS',topic:'',current:'',target:'6.5',exam:'',minutes:60,weak:'均衡'};return `<form id="profile-form">
 <div class="fields">${field('稱呼（選填）',`<input name="name" maxlength="50" autocomplete="given-name" value="${esc(p.name)}" placeholder="怎樣稱呼你？">`)}${field('學習方向',`<select name="course" id="course">${options(['IELTS','自訂'],p.course)}</select>`)}</div>
 <div class="field" id="topic-field" ${p.course==='IELTS'?'hidden':''}><label>學習主題<input name="topic" maxlength="100" value="${esc(p.topic)}" placeholder="例如：DSE 英文、期末考試"></label></div>
 <div class="fields">${field('目前程度（選填）',`<input name="current" maxlength="20" value="${esc(p.current)}" placeholder="例如：雅思 5.5">`)}${field('這次的目標',`<input name="target" maxlength="50" required value="${esc(p.target)}" placeholder="例如：總分 6.5">`)}</div>
 <div class="fields">${field('考試／目標日期（選填）',`<input name="exam" type="date" ${isNew?`min="${dateKey()}"`:''} value="${esc(p.exam)}">`)}${field('每天可用時間（分鐘）',`<input name="minutes" type="number" min="15" max="240" step="1" required value="${p.minutes}">`,'先設定能持續的份量，可隨時調整。')}</div>
 <div class="field" id="weak-field" ${p.course==='自訂'?'hidden':''}><label>優先練習<select name="weak">${options(['均衡','聽力','閱讀','寫作','口說'],p.weak)}</select></label></div>
 <button class="btn full" type="submit">${isNew?'建立我的七日計畫':'儲存目標'}</button>
 <p class="fine">${isNew?'依可用時間與優先項目安排任務；成績只作目標記錄，不用來預測提分。':'修改目標不會覆蓋現有任務。新設定用於下一次產生的計畫。'}</p>
 </form>`}
function setup(){return `<div class="setup"><section class="panel"><span class="eyebrow">YOUR FIRST WEEK</span><h1>先排出做得到的一週。</h1><p class="muted">填下目標，今天就有清楚的下一步。</p>${profileForm(true)}</section><section class="setup-copy"><span class="eyebrow">海外書局出品 · 督學日誌</span><h2>小步前進，<br>讓學習持續發生。</h2><div class="step"><b>01</b><div><strong>計畫要具體</strong><p>把每日可用時間分成練習、檢查與複習。雅思四項技能兼顧，薄弱項目優先。</p></div></div><div class="step"><b>02</b><div><strong>專注於眼前這一項</strong><p>選一個任務，開始計時。完成後留下卡點，讓下一次練習有方向。</p></div></div><div class="step"><b>03</b><div><strong>每週看見自己的節奏</strong><p>回顧完成情況，調整份量。需要真人回饋時，將週報交給督學或老師。</p></div></div><p class="fine">記錄只保存在這部裝置的瀏覽器，不會自動傳送給海外督導或其他人。可匯出備份，或將週報交給你選擇的老師。</p></section></div>`}
function heading(kicker,title,subtitle='',action=''){return `<div class="page-title"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${action}</div>`}
function metricRow(x){return `<div class="metrics"><div class="metric"><label>任務完成</label><strong>${x.done}<small> / ${x.total} 項</small></strong><div class="progress" role="progressbar" aria-label="任務完成率" aria-valuenow="${x.rate}" aria-valuemin="0" aria-valuemax="100"><i style="width:${x.rate}%"></i></div></div><div class="metric"><label>計畫時間</label><strong>${x.planned}<small>分鐘</small></strong></div><div class="metric"><label>已記錄專注</label><strong>${x.focusMinutes}<small>分鐘</small></strong></div></div>`}
function taskCard(t){const cls={'聽力':'listening','寫作':'writing','口說':'speaking'}[t.skill]||'';return `<article class="task ${t.done?'done':''}"><button class="task-check" type="button" aria-label="${t.done?'取消完成':'完成任務'}：${esc(t.title)}" data-action="toggle" data-id="${esc(t.id)}">${t.done?'✓':''}</button><div><div class="task-meta"><span class="tag ${cls}">${t.skill}</span><span>${t.minutes} 分鐘</span>${t.done?'<span>已完成</span>':''}${t.date<today&&!t.done?'<span>待重新安排</span>':''}</div><div class="task-title">${esc(t.title)}</div><div class="task-bottom"><div class="actions">${!t.done?button('開始專注','focus-task','ghost small',`data-id="${esc(t.id)}"`):''}${t.date<today&&!t.done?button('移到今天','move-today','secondary small',`data-id="${esc(t.id)}"`):''}</div><div><button class="icon-btn" data-action="edit-task" data-id="${esc(t.id)}" aria-label="編輯任務：${esc(t.title)}">編輯</button><button class="icon-btn" data-action="delete-task" data-id="${esc(t.id)}" aria-label="刪除任務：${esc(t.title)}">刪除</button></div></div>${t.note?`<p class="task-note">${esc(t.note)}</p>`:''}</div></article>`}
function countdown(){const exam=state.profile.exam;if(!exam)return '按自己的節奏，一項一項完成。';const n=Math.round((new Date(exam+'T12:00:00')-new Date(today+'T12:00:00'))/86400000);return n>0?`距離目標日期還有 ${n} 天。`:n===0?'今天是目標日期，留出休息和準備時間。':'目標日期已過，可以在「目標與資料」設定下一個目標。'}
function timerPanel(){const t=state.timer;const choices=state.tasks.filter(x=>!x.done&&x.date<=today);return `<section class="panel focus-panel"><div class="eyebrow">ONE THING AT A TIME</div><h2 style="margin-top:9px">留一段時間給自己</h2><div class="timer" id="timer-display">${formatTime(t?remaining(t):1500)}</div><div class="timer-caption" id="timer-caption">${t?(t.endAt?'專注進行中':'已暫停'):'一次專注，從 25 分鐘開始'}</div>${t?`<p class="timer-task">${esc(t.title)}</p><div class="actions">${button(t.endAt?'暫停':'繼續','timer-toggle','full')}${button('結束並記錄','timer-finish','secondary full')}${button('取消這次計時','timer-cancel','ghost full')}</div>`:`<div class="field"><label>這次專注的任務<select id="focus-task"><option value="">自由專注</option>${choices.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('')}</select></label></div><div class="field"><label>專注時間（分鐘）<input id="focus-minutes" type="number" min="1" max="240" value="25"></label></div>${button('▶ 開始專注','timer-start','full')}`}<p class="fine muted" style="margin-top:18px">關閉後重新開啟會按經過時間還原計時。到點提示在頁面內顯示，不會在關閉 App 後推送通知。</p></section>`}
function todayView(){const tasks=state.tasks.filter(x=>x.date===today);const missed=state.tasks.filter(x=>x.date<today&&!x.done);return `${heading('TODAY · '+esc(longDate(today)),state.profile.name?`${esc(state.profile.name)}，今天慢慢來。`:'今天，向目標近一步。',esc(countdown()),button('＋ 新增任務','add-task','secondary'))}${metricRow(stats(state,today,today))}<div class="content-grid"><div>${missed.length?`<div class="nudge overdue">有 ${missed.length} 項較早的任務尚未完成。先調整份量，再安排到今天。${button('查看待安排任務','show-overdue','ghost small')}</div>`:''}<div class="section-title"><h2>今天的任務</h2><span>${state.profile.course==='IELTS'?'IELTS 備考':esc(state.profile.topic||'自主學習')}</span></div><div class="task-list">${tasks.length?tasks.map(taskCard).join(''):`<div class="empty"><strong>今天還沒有安排。</strong><p>可以新增一項小任務，或依目標產生七日計畫。</p>${button('產生七日計畫','generate','')}${button('新增任務','add-task','ghost')}</div>`}</div>${tasks.length&&tasks.every(t=>t.done)?'<div class="nudge">今天的任務都完成了。記下最有收穫的一件事，也給自己留一點休息時間。</div>':''}<p class="inline-note">使用自己的教材或合法公開練習資源；完成任務代表學習記錄，不等同正式能力評分。</p></div><div>${timerPanel()}<section class="panel"><h2>練習入口</h2><ul class="help-list"><li><a href="https://ielts.org/take-a-test/preparation-resources" target="_blank" rel="noopener">IELTS 官方備考資源 ↗</a><small>按 Academic 或 General Training 選擇材料。</small></li><li><a href="/apps/advanced-vocabulary/" target="_blank" rel="noopener">OTC 英語詞彙練習 ↗</a><small>配合閱讀與聽力整理不熟悉的詞語。</small></li><li><a href="/apps/">OTC 學習工具目錄 ↗</a></li></ul></section></div></div>`}
let showOverdue=false;
function planView(){const days=Array.from({length:7},(_,i)=>addDays(weekStart,i));const tasks=showOverdue?state.tasks.filter(t=>t.date<today&&!t.done):state.tasks.filter(t=>t.date===selectedDay);return `${heading('A LITTLE, EVERY DAY','把一週，拆成每天。','點選日期查看任務；計畫可以配合你的實際時間調整。',button('＋ 新增','add-task','secondary'))}<div class="week-nav">${button('‹ 前七日','prev-week','secondary','aria-label="前七日"')}<strong>${weekStart} — ${addDays(weekStart,6)}</strong>${button('後七日 ›','next-week','secondary','aria-label="後七日"')}</div><div class="days">${days.map(d=>{const s=stats(state,d,d);return `<button class="day" data-action="day" data-date="${d}" aria-pressed="${selectedDay===d&&!showOverdue}" aria-label="${longDate(d)}，完成 ${s.done} 項，共 ${s.total} 項"><span>${new Date(d+'T12:00:00').toLocaleDateString('zh-Hant',{weekday:'short'})}</span><strong>${Number(d.slice(-2))}</strong><small>${s.done}/${s.total}</small><span class="dot ${s.total?'has':''}"></span></button>`}).join('')}</div><div class="content-grid"><section><div class="section-title"><h2>${showOverdue?'較早未完成的任務':esc(longDate(selectedDay))}</h2>${button('回到今天','plan-today','ghost small')}</div><div class="task-list">${tasks.length?tasks.map(taskCard).join(''):'<div class="empty"><strong>留一點彈性給自己。</strong><p>這裡沒有待辦任務；可新增練習或保留休息時間。</p></div>'}</div></section><section class="panel"><span class="eyebrow">NEXT SEVEN DAYS</span><h2 style="margin-top:10px">接下來怎樣安排？</h2><p class="muted">目前每天設定 ${state.profile.minutes} 分鐘。可依目標補上接下來七日尚未排任務的日期。</p>${button('補上接下來七日計畫','generate','full')}<p class="fine">保留已有任務；以今天起算七日，只填入尚無任務的日期，最多排到目標日期。</p><div class="nudge">任務太多時，先縮小範圍或調整日期。保持可持續的節奏。</div>${button('查看所有待安排任務','show-overdue','ghost full')}</section></div>`}
function reportText(start=addDays(today,-6)){const end=addDays(start,6),s=stats(state,start,end),p=state.profile,r=state.reviews[start]||{win:'',block:'',next:''};return `督學日誌｜學習週報\n${start} 至 ${end}\n${p?.name||'學習者'}｜${p?.course==='IELTS'?'IELTS':p?.topic||'自主學習'}｜目標：${p?.target||'未設定'}\n\n按排定日期統計：完成 ${s.done}/${s.total} 項（${s.rate}%）\n計畫 ${s.planned} 分鐘；已完成任務的預估時間 ${s.completedMinutes} 分鐘\n計時器記錄：${s.focusMinutes} 分鐘\n\n最有收穫：${r.win||'尚未填寫'}\n遇到的卡點：${r.block||'尚未填寫'}\n下一週調整：${r.next||'尚未填寫'}\n\n任務記錄\n${state.tasks.filter(t=>t.date>=start&&t.date<=end).map(t=>`${t.done?'✓':'○'} ${t.date}｜${t.skill}｜${t.title}${t.note?'\n  筆記：'+t.note:''}`).join('\n')||'尚無任務'}\n\n海外書局出品 · OTC 學習平台\n完成記錄不代表正式考試分數；本週報由使用者自行匯出。`}
function reviewView(){const start=addDays(today,-6),s=stats(state,start,today),r=state.reviews[start]||{win:'',block:'',next:''};const days=Array.from({length:7},(_,i)=>addDays(start,i));return `${heading('REFLECT & RESET','看見進度，也看見卡點。',`${start} — ${today} · 最近七日`)}${metricRow(s)}<div class="content-grid"><section class="panel"><div class="section-title"><h2>每天的完成情況</h2><span>依任務排定日期統計</span></div><div class="bars">${days.map(d=>{const x=stats(state,d,d);return `<div class="bar-col"><strong>${x.total?x.rate+'%':'—'}</strong><div class="bar-track" role="img" aria-label="${d} 完成 ${x.done}/${x.total} 項"><span style="height:${x.rate}%"></span></div><small>${d.slice(5).replace('-','/')}</small></div>`}).join('')}</div><div class="nudge">${!s.total?'尚未有任務記錄。先安排一小段時間，完成後再回來看。':s.rate>=80?'近期的執行節奏穩定。回顧最常卡住的內容，再決定是否調整練習重點。':s.rate>=40?'已有一部分任務完成。看看未完成項目是時間不夠，還是題目與材料太難。':'先把任務縮到能完成的份量。保留最重要的一項，找出中斷的原因。'}</div><h2>我的每週回顧</h2><form id="review-form" class="review-form">${field('這週最有收穫的是什麼？',`<textarea name="win" maxlength="2000" placeholder="例如：閱讀定位比上週更清楚。">${esc(r.win)}</textarea>`)}${field('什麼讓我停下來？',`<textarea name="block" maxlength="2000" placeholder="時間不足、材料太難，或是不知道怎樣開始？">${esc(r.block)}</textarea>`)}${field('下一週做一個什麼調整？',`<textarea name="next" maxlength="2000" placeholder="例如：每天先做 15 分鐘聽力，再安排其他任務。">${esc(r.next)}</textarea>`)}<button class="btn" type="submit">儲存這次回顧</button></form>${Object.keys(state.reviews).length?`<details class="section-spacer"><summary>已儲存的回顧（${Object.keys(state.reviews).length}）</summary>${Object.entries(state.reviews).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,12).map(([date,r])=>`<div class="report-box" style="margin-top:12px"><strong>${date} — ${addDays(date,6)}</strong>\n收穫：${esc(r.win)||'—'}\n卡點：${esc(r.block)||'—'}\n調整：${esc(r.next)||'—'}</div>`).join('')}</details>`:''}</section><div><section class="panel"><span class="eyebrow">YOUR WEEKLY NOTE</span><h2 style="margin-top:10px">帶著記錄，尋找回饋。</h2><p class="muted">將週報交給你的督學、老師，或留給下週的自己。</p><div class="actions report-actions">${button('複製週報','copy-report','')}${button('下載週報','download-report','secondary')}</div><p class="fine">先儲存回顧再匯出。複製或下載不會自動傳送給任何人。</p><a class="btn secondary full" href="mailto:office@overseasuk.com?subject=%E7%9D%A3%E5%AD%B8%E6%97%A5%E8%AA%8C%EF%BD%9C%E4%BA%BA%E5%B7%A5%E5%9B%9E%E9%A5%8B%E8%AB%AE%E8%A9%A2">諮詢真人督學 ↗</a><p class="fine">如需批改、口說或定期回饋，先確認服務範圍、時段及費用。</p></section><section class="panel"><h2>最近的專注記錄</h2><ul class="history-list">${state.sessions.length?state.sessions.slice(-8).reverse().map(x=>`<li><span>${esc(x.title)}<br><small>${x.date}</small></span><small>${Math.floor(x.seconds/60)} 分 ${Math.round(x.seconds%60)} 秒</small></li>`).join(''):'<li class="muted">計時完成或結束並記錄後，會出現在這裡。</li>'}</ul></section></div></div>`}
function settingsView(){return `${heading('MAKE IT YOURS','目標可以調整，記錄值得保留。','學習資料保存在這部裝置的瀏覽器。')}<div class="content-grid"><section class="panel"><h2 style="margin-bottom:23px">我的學習目標</h2>${profileForm(!state.profile)}</section><div><section class="panel"><h2>備份與還原</h2><p class="muted">更換裝置或清除瀏覽器資料前，先下載備份。</p><div class="stack">${button('下載完整備份（JSON）','export','secondary full')}<label class="btn secondary full" for="import-file">選擇備份檔並還原<input type="file" id="import-file" accept=".json,application/json" hidden></label></div><p class="fine">還原會在確認後取代此裝置的現有記錄。備份包含目標、任務、專注與回顧，請自行妥善保管。</p></section><section class="panel"><h2>關於督學日誌</h2><p>海外書局出品<br><span class="muted">OTC 學習平台 · 本機版 1.0</span></p><p class="fine">這是自助學習規劃工具，依時間與優先項目產生任務，沒有接入真人監看或自動評分。頁面關閉時不提供通知；資料不會跨裝置自動同步。</p><p class="fine">手機可使用瀏覽器的「加入主畫面」功能。開啟 App 需要網絡連線。</p><a href="/learning-platform/">返回 OTC 學習平台 ↗</a></section><section class="panel"><h2>清除本機記錄</h2><p class="fine">只影響此瀏覽器，無法復原；建議先下載備份。</p>${button('清除全部資料','reset','danger')}</section></div></div>`}
function render(){today=dateKey();document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('main').innerHTML=!state.profile&&view!=='settings'?setup():({today:todayView,plan:planView,review:reviewView,settings:settingsView}[view])();bindForms()}
function bindForms(){const form=$('profile-form');if(form){$('course').addEventListener('change',()=>{$('topic-field').hidden=$('course').value==='IELTS';$('weak-field').hidden=$('course').value==='自訂'});form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),p={name:String(d.get('name')).trim(),course:d.get('course'),topic:String(d.get('topic')).trim(),current:String(d.get('current')).trim(),target:String(d.get('target')).trim(),exam:d.get('exam'),minutes:Number(d.get('minutes')),weak:d.get('weak')};if(!validProfile(p)||!p.target){toast('請檢查目標、日期及每日時間。');return}if(p.exam&&p.exam<today){toast('目標日期已過，請設定今天或之後的日期。');return}const fresh=!state.profile;state.profile=p;if(fresh)state.tasks.push(...generatePlan(p,today,state.tasks));save();navigate('today');toast(fresh?'七日計畫已建立，先從今天的一項開始。':'目標已儲存，現有任務保持不變。')})}const review=$('review-form');if(review)review.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(review);state.reviews[addDays(today,-6)]={win:String(d.get('win')).trim(),block:String(d.get('block')).trim(),next:String(d.get('next')).trim()};save();render();toast('本次回顧已儲存。')});const input=$('import-file');if(input)input.addEventListener('change',importBackup)}
function openDialog(html){$('dialog-content').innerHTML=html;$('task-dialog').showModal()}
function closeDialog(){$('task-dialog').close()}
function editTask(id){const t=state.tasks.find(t=>t.id===id)||{id:null,title:'',skill:state.profile?.course==='自訂'?'自訂':'閱讀',date:view==='plan'?selectedDay:today,minutes:25};openDialog(`<div class="dialog-top"><h2 id="dialog-title">${t.id?'編輯任務':'新增一項任務'}</h2>${button('✕','close-dialog','ghost small','aria-label="關閉"')}</div><form id="task-form">${field('這次具體要完成什麼？',`<input name="title" maxlength="160" required value="${esc(t.title)}" placeholder="例如：閱讀一篇材料，整理三個錯題">`)}<div class="fields">${field('類別',`<select name="skill">${options(SKILLS,t.skill)}</select>`)}${field('預計時間（分鐘）',`<input name="minutes" type="number" min="1" max="240" step="1" required value="${t.minutes}">`)}</div>${field('安排日期',`<input name="date" type="date" required value="${t.date}">`)}<button class="btn full" type="submit">儲存任務</button></form>`);$('task-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);const changes={title:String(d.get('title')).trim(),skill:d.get('skill'),minutes:Number(d.get('minutes')),date:d.get('date')};if(!changes.title||changes.title.length>160||!isDate(changes.date)||!Number.isInteger(changes.minutes)||changes.minutes<1||changes.minutes>240||!SKILLS.includes(changes.skill)){toast('請填妥任務、日期與時間。');return}if(t.id)Object.assign(t,changes);else state.tasks.push({...changes,id:uid(),done:false,note:'',completedAt:null});save();closeDialog();render();toast('任務已儲存。')})}
function completeTask(id){const t=state.tasks.find(t=>t.id===id);if(!t)return;if(t.done){setCompletion(state,id,false,t.note);save();render();toast('已恢復為待完成，筆記保留。');return}openDialog(`<div class="dialog-top"><h2 id="dialog-title">完成，也留下下一步。</h2>${button('✕','close-dialog','ghost small','aria-label="關閉"')}</div><p>${esc(t.title)}</p><form id="complete-form">${field('收穫或卡點（選填）',`<textarea name="note" maxlength="2000" placeholder="例如：定位答案沒問題，但同義替換還不熟。">${esc(t.note)}</textarea>`)}<p class="fine">打卡只記錄任務完成。實際專注時間由計時器另行記錄。</p><button class="btn full" type="submit">✓ 完成這一項</button></form>`);$('complete-form').addEventListener('submit',e=>{e.preventDefault();setCompletion(state,id,true,String(new FormData(e.target).get('note')).trim());save();closeDialog();render();toast('又完成一小步。')})}
function formatTime(s){const n=Math.max(0,Math.ceil(s));return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function startTimer(id,mins){if(state.timer){toast('已有計時，請先暫停、記錄或取消。');navigate('today');return}const task=state.tasks.find(t=>t.id===id);if(!Number.isInteger(mins)||mins<1||mins>240){toast('請填入 1 至 240 分鐘。');return}state.timer={taskId:task?.id||'',title:task?.title||'自由專注',duration:mins*60,remaining:mins*60,endAt:Date.now()+mins*60000};save();navigate('today');$('timer-display')?.scrollIntoView({block:'center',behavior:'smooth'})}
function finishTimer(automatic=false){const t=state.timer;if(!t)return;const elapsed=Math.max(0,Math.min(t.duration,t.duration-remaining(t)));if(elapsed>0)state.sessions.push({id:uid(),date:dateKey(),title:t.title,seconds:elapsed});state.timer=null;save();render();toast(automatic?'這段專注已完成。稍作休息，再為任務打卡。':elapsed>0?'這次專注已記錄，任務完成後記得打卡。':'尚未累積專注時間。')}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function importBackup(e){const f=e.target.files[0];if(!f)return;try{if(f.size>5_000_000)throw new Error('備份檔超過 5 MB，請檢查是否選錯檔案。');const next=validateState(JSON.parse(await f.text()));if(!confirm('以此備份取代本機所有目標、任務及回顧？目前計時也會停止。建議先下載現有備份。'))return;next.timer=null;const encoded=JSON.stringify(next);try{localStorage.setItem(KEY,encoded)}catch{throw new Error('此瀏覽器目前無法儲存還原資料，現有記錄未變更。')}state=next;storageCorrupt=false;save();navigate(state.profile?'today':'settings');toast('備份已還原。')}catch(err){toast(err.message||'無法讀取備份，現有記錄未變更。')}finally{e.target.value=''}}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav){navigate(nav.dataset.view);return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
 if(a==='add-task')editTask();
 if(a==='edit-task')editTask(id);
 if(a==='toggle')completeTask(id);
 if(a==='close-dialog')closeDialog();
 if(a==='delete-task'){const t=state.tasks.find(t=>t.id===id);if(t&&confirm(`刪除「${t.title}」及其完成筆記？`)){state.tasks=state.tasks.filter(t=>t.id!==id);save();render();toast('任務已刪除，專注記錄保留。')}}
 if(a==='move-today'){const t=state.tasks.find(t=>t.id===id);if(t){const total=stats(state,today,today).planned+t.minutes;if(total>state.profile.minutes&&!confirm(`移入後今天共有 ${total} 分鐘，超過設定的 ${state.profile.minutes} 分鐘。仍要移入嗎？`))return;t.date=today;save();render();toast('已移到今天。')}}
 if(a==='day'){selectedDay=b.dataset.date;showOverdue=false;render()}
 if(a==='prev-week'||a==='next-week'){weekStart=addDays(weekStart,a==='prev-week'?-7:7);selectedDay=weekStart;showOverdue=false;render()}
 if(a==='plan-today'){weekStart=today;selectedDay=today;showOverdue=false;render()}
 if(a==='show-overdue'){showOverdue=true;navigate('plan')}
 if(a==='generate'){if(!state.profile){navigate('settings');return}const items=generatePlan(state.profile,today,state.tasks);if(!items.length){toast('接下來七日已有安排，或目標日期已過。可手動新增或調整目標。');return}state.tasks.push(...items);save();render();toast(`已新增 ${new Set(items.map(t=>t.date)).size} 天的計畫，原有任務保留。`)}
 if(a==='focus-task'){const t=state.tasks.find(t=>t.id===id);if(t)startTimer(id,Math.min(t.minutes,25))}
 if(a==='timer-start')startTimer($('focus-task').value,Number($('focus-minutes').value));
 if(a==='timer-toggle'){const t=state.timer;if(!t)return;if(t.endAt){t.remaining=remaining(t);t.endAt=null}else t.endAt=Date.now()+t.remaining*1000;save();render()}
 if(a==='timer-finish')finishTimer();
 if(a==='timer-cancel'&&confirm('取消這次計時？本次經過的時間不會記入專注記錄。')){state.timer=null;save();render()}
 if(a==='export'){const copy=structuredClone(state);if(copy.timer){copy.timer.remaining=remaining(copy.timer);copy.timer.endAt=null}download(`otc-study-backup-${today}.json`,JSON.stringify(copy,null,2),'application/json');toast('備份下載已開始。')}
 if(a==='copy-report'){try{await navigator.clipboard.writeText(reportText());toast('週報已複製，可自行貼給老師。')}catch{openDialog(`<div class="dialog-top"><h2 id="dialog-title">複製學習週報</h2>${button('✕','close-dialog','ghost small','aria-label="關閉"')}</div><p class="fine">瀏覽器未允許自動複製，請選取以下文字手動複製。</p><textarea id="manual-report" rows="14" readonly aria-label="學習週報">${esc(reportText())}</textarea>`);$('manual-report').select()}}
 if(a==='download-report')download(`otc-study-report-${today}.txt`,reportText(),'text/plain;charset=utf-8');
 if(a==='reset'&&confirm('確定清除這個瀏覽器的全部學習資料？此動作無法復原。')){try{localStorage.removeItem(KEY)}catch{toast('瀏覽器無法清除資料，請檢查儲存設定。');return}state=emptyState();storageCorrupt=false;save();navigate('today');toast('本機資料已清除。')}
});
function tick(){if(state.timer?.endAt&&remaining(state.timer)<=0){finishTimer(true);return}const display=$('timer-display');if(display&&state.timer)display.textContent=formatTime(remaining(state.timer));if(today!==dateKey()){today=dateKey();render()}}
setInterval(tick,1000);document.addEventListener('visibilitychange',tick);
window.addEventListener('storage',e=>{if(e.key===KEY){try{state=e.newValue?validateState(JSON.parse(e.newValue)):emptyState();storageCorrupt=false;closeDialog();render();toast('已同步此裝置另一個分頁的變更。')}catch{warn('另一個分頁的資料無法讀取，請先備份目前記錄。')}}});
render();tick();
